include_defs('//gerrit-acceptance-tests/tests.defs')

acceptance_tests(
  group = 'rest_project',
  srcs = glob(['*IT.java']),
  deps = [
    ':project',
    ':refassert',
  ],
  labels = ['rest'],
)

java_library(
  name = 'refassert',
  srcs = [
    'RefAssert.java',
  ],
  deps = [
    '//lib:truth',
    '//gerrit-extension-api:api',
    '//gerrit-server:server',
  ],
)

java_library(
  name = 'project',
  srcs = [
    'ProjectAssert.java',
  ],
  deps = [
    '//gerrit-extension-api:api',
    '//gerrit-reviewdb:server',
    '//gerrit-server:server',
    '//lib:gwtorm',
    '//lib:truth',
  ],
)
