- job:
    name: gerrit-base
    parent: gerrit-setup
    description: |
      Base job for all Gerrit-related builds

      This adds required projects needed for all Gerrit-related builds
      (i.e., builds of Gerrit itself or plugins) on this branch.
    required-projects:
      - plugins/codemirror-editor
      - plugins/commit-message-length-validator
      - plugins/download-commands
      - plugins/hooks
      - plugins/replication
      - plugins/reviewnotes
      - plugins/singleusergroup

- job:
    name: gerrit-build
    parent: gerrit-build-base
    description: |
      Build Gerrit

      This builds Gerrit with the core plugins.
    # This inherits from gerrit-base, so submodules listed above do
    # not need to be repeated here.

- project:
    check:
      jobs:
        - gerrit-build
