- job:
    name: gerrit-build
    parent: gerrit-build-base
    description: Build Gerrit
    required-projects:
      - plugins/codemirror-editor
      - plugins/commit-message-length-validator
      - plugins/delete-project
      - plugins/download-commands
      - plugins/gitiles
      - plugins/hooks
      - plugins/plugin-manager
      - plugins/replication
      - plugins/reviewnotes
      - plugins/singleusergroup
      - plugins/webhooks
      - polymer-bridges

- project:
    check:
      jobs:
        - gerrit-build
