# TODO(davido): Migrate all dependencies from WORKSPACE to MODULE.bazel
# https://issues.gerritcodereview.com/issues/303819949

bazel_dep(name = "bazel_features", version = "1.39.0")
bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "rules_jvm_external", version = "6.9")
bazel_dep(name = "rules_shell", version = "0.6.1")

# nongoogle bazel_deps
bazel_dep(name = "rules_java", version = "8.16.1")
bazel_dep(name = "rules_proto", version = "7.1.0")

# This must come BEFORE bazel_dep(name = "protobuf")
# because they register the from-source toolchain,
# and the first registration wins.
bazel_dep(name = "toolchains_protoc", version = "0.6.0")

protoc = use_extension("@toolchains_protoc//protoc:extensions.bzl", "protoc")
protoc.toolchain(
    google_protobuf = "com_google_protobuf",
    version = "v33.0",
)

bazel_dep(name = "protobuf", version = "33.2")

# TODO(davido): Use a proper release once the prebuilt toolchain is available there.
# https://github.com/protocolbuffers/protobuf/issues/19558
git_override(
    module_name = "protobuf",
    commit = "cc23698b486e690ea2eb873cc7596a87c74a3ba6",
    remote = "https://github.com/protocolbuffers/protobuf",
)

bazel_dep(name = "jgit")
local_path_override(
    module_name = "jgit",
    path = "./modules/jgit",
)

bazel_dep(name = "rbe_autoconfig")
git_override(
    module_name = "rbe_autoconfig",
    commit = "c4d733d0399ebf2ee1ffb897be5fbaba23738e04",
    remote = "https://github.com/davido/rbe_autoconfig.git",
)

register_toolchains("//tools:all")

maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven")

# Empty maven.install call to apply the configuration to the installation from
# toml files.
maven.install(
    name = "gerrit_deps",
    artifacts = [],
    repositories = [
        "https://repo1.maven.org/maven2",
        "https://gerrit-maven.storage.googleapis.com",
    ],
    lock_file = "//:maven_install.json",
    duplicate_version_warning = "error",
    fail_on_missing_checksum = True,
    fetch_sources = True,
    strict_visibility = True,
    version_conflict_policy = "pinned",
)

maven.from_toml(
    name = "gerrit_deps",
    libs_versions_toml = "//tools:deps.toml",
)

use_repo(maven, "gerrit_deps")

maven.install(
    name = "gerrit_nongoogle_deps",
    artifacts = [],
    repositories = [
        "https://repo1.maven.org/maven2",
    ],
    lock_file = "//:maven_install_nongoogle.json",
    duplicate_version_warning = "error",
    fail_on_missing_checksum = True,
    fetch_sources = True,
    strict_visibility = True,
    version_conflict_policy = "pinned",
)

maven.from_toml(
    name = "gerrit_nongoogle_deps",
    libs_versions_toml = "//tools:nongoogle.toml",
)

use_repo(maven, "gerrit_nongoogle_deps")
