// Copyright (C) 2012 The Android Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package com.google.gerrit.server.git;

import com.google.gerrit.extensions.annotations.ExtensionPoint;
import com.google.gerrit.reviewdb.client.Change;
import com.google.gerrit.server.project.ChangeControl;
import com.google.gerrit.server.project.ProjectState;

import org.eclipse.jgit.revwalk.RevCommit;

/**
 * Allows to modify message for new commits generated by submit strategies.
 *
 * Invoked by Gerrit when all information about new commit is already known such
 * as parent(s), tree hash, etc, but commit's message can still be modified.
 */
@ExtensionPoint
public interface ChangeMessageModifier {

  /**
   * @param newCommitMessage
   * @param original
   * @param mergeTip
   * @param ctl
   * @return
   */
  String onCommitBeingCreated(String newCommitMessage, RevCommit original,
      RevCommit mergeTip, ChangeControl ctl);
}
