// Copyright (C) 2026 The Android Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package com.google.gerrit.server.notedb;

import static com.google.common.truth.Truth.assertThat;
import static com.google.gerrit.testing.TestActionRefUpdateContext.testRefAction;

import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableSet;
import com.google.gerrit.entities.AttentionSetUpdate;
import com.google.gerrit.entities.Change;
import com.google.gerrit.entities.LabelId;
import com.google.gerrit.entities.PatchSet;
import com.google.gerrit.entities.SubmissionId;
import com.google.gerrit.server.notedb.ChangeNotesCommit.ChangeNotesRevWalk;
import com.google.inject.Inject;
import java.util.concurrent.TimeUnit;
import org.eclipse.jgit.lib.ObjectId;
import org.eclipse.jgit.revwalk.RevCommit;
import org.junit.Test;

public class ChangeNotesParserBenchmarkTest extends AbstractChangeNotesTest {
  @Inject private ChangeNoteJson changeNoteJson;

  @Test
  public void benchmarkParseMultiplePatchSetsAndFooters() throws Exception {
    Change c = newChange();
    int numPatchSets = 30;

    for (int i = 2; i <= numPatchSets; i++) {
      int psNum = i;
      RevCommit commit = tr.commit().message("PS" + psNum).create();
      testRefAction(
          () -> {
            ChangeUpdate u = newUpdate(c, changeOwner);
            u.setPatchSetId(PatchSet.id(c.getId(), psNum));
            u.setCommit(rw, commit);
            u.putApproval(LabelId.CODE_REVIEW, (short) 1);
            u.putReviewer(otherUser.getAccount().id(), ReviewerStateInternal.REVIEWER);
            u.putReviewer(otherUser.getAccount().id(), ReviewerStateInternal.CC);
            u.addToPlannedAttentionSetUpdates(
                ImmutableSet.of(
                    AttentionSetUpdate.createForWrite(
                        otherUser.getAccount().id(),
                        AttentionSetUpdate.Operation.ADD,
                        "Added for review")));
            u.addCustomKeyedValue("custom-key-" + psNum, "value-" + psNum);
            u.setTag("autogenerated:tag");
            u.setChangeMessage("Uploaded patch set " + psNum);
            u.commit();
          });
    }

    testRefAction(
        () -> {
          ChangeUpdate u = newUpdate(c, changeOwner);
          u.merge(
              new SubmissionId(c),
              ImmutableList.of(
                  submitRecord(
                      "OK",
                      null,
                      submitLabel(LabelId.CODE_REVIEW, "OK", changeOwner.getAccountId()))));
          u.commit();
        });

    ChangeNotes notes = newNotes(c);
    ObjectId tip = notes.getRevision();

    // Warmup
    for (int i = 0; i < 200; i++) {
      try (ChangeNotesRevWalk walk = ChangeNotesCommit.newRevWalk(repo)) {
        ChangeNotesParser parser =
            new ChangeNotesParser(
                c.getId(),
                tip,
                walk,
                changeNoteJson,
                args.metrics,
                new NoteDbUtil(serverId, externalIdCache));
        ChangeNotesState state = parser.parseAll();
        assertThat(state.patchSets()).hasSize(numPatchSets);
      }
    }

    // Benchmark iterations
    int iterations = 1000;
    long start = System.nanoTime();
    for (int i = 0; i < iterations; i++) {
      try (ChangeNotesRevWalk walk = ChangeNotesCommit.newRevWalk(repo)) {
        ChangeNotesParser parser =
            new ChangeNotesParser(
                c.getId(),
                tip,
                walk,
                changeNoteJson,
                args.metrics,
                new NoteDbUtil(serverId, externalIdCache));
        ChangeNotesState state = parser.parseAll();
        assertThat(state.patchSets()).hasSize(numPatchSets);
      }
    }
    long elapsedNanos = System.nanoTime() - start;
    double avgMs = (double) elapsedNanos / (iterations * 1_000_000.0);
    double avgUs = (double) elapsedNanos / (iterations * 1_000.0);
    System.out.printf(
        "NoteDb Parse Benchmark (%d commits): total = %d ms, avg = %.3f ms (%.1f µs) per parse%n",
        numPatchSets + 1, TimeUnit.NANOSECONDS.toMillis(elapsedNanos), avgMs, avgUs);
  }
}
