-- Gerrit 2 : MySQL
--
delimiter //

CREATE FUNCTION nextval_account_id ()
  RETURNS BIGINT
  LANGUAGE SQL
  NOT DETERMINISTIC
  MODIFIES SQL DATA
BEGIN
  INSERT INTO account_id (s) VALUES (NULL);
  RETURN LAST_INSERT_ID();
END;
//
