(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ca(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var da=ca(this);function ea(a,b){if(b)a:{var c=da;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ba(c,a,{configurable:!0,writable:!0,value:b})}}
ea("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,h){this.l=f;ba(this,"description",{configurable:!0,writable:!0,value:h})}if(a)return a;c.prototype.toString=function(){return this.l};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",e=0;return b});
ea("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=da[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&ba(d.prototype,a,{configurable:!0,writable:!0,value:function(){return fa(aa(this))}})}return a});function fa(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}var x=this||self;
function ha(a){return a};/*

 Copyright 2022 Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
function z(a,b,c,d){var e=arguments.length,f=3>e?b:null===d?d=Object.getOwnPropertyDescriptor(b,c):d,h;if("object"===typeof Reflect&&Reflect&&"function"===typeof Reflect.decorate)f=Reflect.decorate(a,b,c,d);else for(var k=a.length-1;0<=k;k--)if(h=a[k])f=(3>e?h(f):3<e?h(b,c,f):h(b,c))||f;return 3<e&&f&&Object.defineProperty(b,c,f),f}function A(a){if("object"===typeof Reflect&&Reflect&&"function"===typeof Reflect.metadata)return Reflect.metadata("design:type",a)};var ia=!/^\s*class\s*\{\s*\}\s*$/.test(class{}.toString());function ja(a,b=`unexpected value ${a}!`){throw Error(b);};var B;function ka(){if(void 0===B){var a=null,b=x.trustedTypes;if(b&&b.createPolicy){try{a=b.createPolicy("goog#html",{createHTML:ha,createScript:ha,createScriptURL:ha})}catch(c){x.console&&x.console.error(c.message)}B=a}else B=a}return B};function C(a,b){this.g=a===la&&b||"";this.v=ma}C.prototype.va=!0;C.prototype.l=function(){return this.g};var ma={},la={};const na={};class oa{constructor(a,b){this.g=b===na?a:"";this.va=!0}toString(){return this.g.toString()}l(){return this.g.toString()}};var D=class{constructor(a,b){this.g=b===pa?a:""}toString(){return this.g+""}};D.prototype.va=!0;D.prototype.l=function(){return this.g.toString()};function qa(a){return a instanceof D&&a.constructor===D?a.g:"type_error:TrustedResourceUrl"}var pa={};function ra(a){const b=ka();a=b?b.createScriptURL(a):a;return new D(a,pa)};var E=class{constructor(a,b){this.g=b===sa?a:""}toString(){return this.g.toString()}};E.prototype.va=!0;E.prototype.l=function(){return this.g.toString()};var sa={};const ta={};class ua{constructor(a,b){this.g=b===ta?a:"";this.va=!0}l(){return this.g}toString(){return this.g.toString()}};const va={};function wa(a){return a instanceof F&&a.constructor===F?a.g:"type_error:SafeHtml"}class F{constructor(a,b){this.g=b===va?a:"";this.va=!0}l(){return this.g.toString()}toString(){return this.g.toString()}};/*

 SPDX-License-Identifier: Apache-2.0
*/
class xa{constructor(a){this.fc=a}}function G(a){return new xa(b=>b.substr(0,a.length+1).toLowerCase()===a+":")}const ya=[G("data"),G("http"),G("https"),G("mailto"),G("ftp"),new xa(a=>/^[^:]*([/?#]|$)/.test(a))];function za(a,...b){if(0===b.length)return ra(a[0]);const c=[a[0]];for(let d=0;d<b.length;d++)c.push(encodeURIComponent(b[d])),c.push(a[d+1]);return ra(c.join(""))};/*

 Copyright 2017 Google LLC
 SPDX-License-Identifier: BSD-3-Clause
*/
const Aa=(a,b)=>({kind:b.kind,elements:b.elements,cb(c){customElements.define(a,c)}});var Ba=({cb:a,wa:b})=>(c,d)=>{if(void 0!==d){var e=c.constructor;void 0!==b&&Object.defineProperty(c,d,b(d));null==a||a(e,d)}else{const f=null!=(e=c.ic)?e:c.key;c=void 0!=b?{kind:"method",jc:"prototype",key:f,wa:b(c.key)}:{...c,key:f};void 0!=a&&(c.cb=function(h){a(h,f)});return c}};const Da=(a,b)=>"method"!==b.kind||!b.wa||"value"in b.wa?{kind:"field",key:Symbol(),jc:"own",wa:{},ic:b.key,sb(){"function"===typeof b.sb&&(this[b.key]=b.sb.call(this))},cb(c){Ca(c,b.key,a)}}:{...b,cb(c){Ca(c,b.key,a)}};function H(a){return(b,c)=>{void 0!==c?(Ca(b.constructor,c,a),b=void 0):b=Da(a,b);return b}};const Ea=new Set,Fa=new Map,Ga=(a,b)=>{if(void 0!==window.ShadyCSS&&(!window.ShadyCSS.nativeShadow||window.ShadyCSS.ApplyShim)){var c,d,e=(null==(c=window.ShadyDOM)?0:c.inUse)&&!0===(null==(d=window.ShadyDOM)?void 0:d.noPatch)?window.ShadyDOM.wrap:n=>n,f=n=>void 0!==n&&!Ea.has(n),h=n=>{let p=Fa.get(n);void 0===p&&Fa.set(n,p=[]);return p},k=(n,p)=>{const t=h(n),m=0!==t.length;if(m){const r=document.createElement("style");r.textContent=t.join("\n");p.content.appendChild(r)}Ea.add(n);Fa.delete(n);window.ShadyCSS.prepareTemplateStyles(p,
n);m&&window.ShadyCSS.nativeShadow&&(n=p.content.querySelector("style"),null!==n&&p.content.appendChild(n))},g=new Map,l=a.createElement;a.createElement=function(n,p){n=l.call(a,n,p);p=null==p?void 0:p.scope;if(void 0!==p&&(window.ShadyCSS.nativeShadow||window.ShadyCSS.prepareTemplateDom(n,p),f(p))){p=h(p);const t=n.content.querySelectorAll("style");p.push(...Array.from(t).map(m=>{let r;null==(r=m.parentNode)||r.removeChild(m);return m.textContent}))}return n};var u=document.createDocumentFragment(),
q=document.createComment("");b=b.prototype;var w=b.ga;b.ga=function(n,p=this){const t=e(this.ha).parentNode;var m,r=null==(m=this.options)?void 0:m.scope,y;if((t instanceof ShadowRoot||t===(null==(y=this.options)?void 0:y.fd))&&f(r)){m=this.ha;y=this.pa;u.appendChild(q);this.ha=q;this.pa=null;w.call(this,n,p);n=(null==n?0:n._$litType$)?this.j.gb.ua:document.createElement("template");k(r,n);u.removeChild(q);let v;if(null==(v=window.ShadyCSS)?0:v.nativeShadow)r=n.content.querySelector("style"),null!==
r&&u.appendChild(r.cloneNode(!0));t.insertBefore(u,y);this.ha=m;this.pa=y}else w.call(this,n,p)};b.nb=function(n){var p,t=null==(p=this.options)?void 0:p.scope;p=g.get(t);void 0===p&&g.set(t,p=new Map);t=p.get(n.fa);void 0===t&&p.set(n.fa,t=new a(n,this.options));return t}}};let Ha;null!=(Ha=window).litHtmlPolyfillSupport||(Ha.litHtmlPolyfillSupport=Ga);let Ia="";if(window.Symbol){const a=Symbol();"symbol"!==typeof a&&(Ia=Object.keys(a)[0])}const Ja=""!==Ia;
var Ka=Ja?a=>null!=a&&void 0!==a[Ia]:()=>!1;if(Ja&&!window.Symbol.for){const a=new Map;window.Symbol.for=b=>{a.has(b)||a.set(b,Symbol(b));return a.get(b)}};const La=({ReactiveElement:a})=>{if(void 0!==window.ShadyCSS&&(!window.ShadyCSS.nativeShadow||window.ShadyCSS.ApplyShim)){a=a.prototype;window.ShadyDOM&&window.ShadyDOM.inUse&&!0===window.ShadyDOM.noPatch&&window.ShadyDOM.patchElementProto(a);var b=a.la;a.la=function(){const e=this.localName;if(window.ShadyCSS.nativeShadow)return b.call(this);if(!this.constructor.hasOwnProperty("__scoped")){this.constructor.__scoped=!0;const h=this.constructor.jb.map(l=>l instanceof CSSStyleSheet?Array.from(l.cssRules).reduce((u,
q)=>u+q.cssText,""):l.cssText);let k,g;null==(k=window.ShadyCSS)||null==(g=k.ScopingShim)||g.prepareAdoptedCssText(h,e);void 0===this.constructor.zb&&window.ShadyCSS.prepareTemplateStyles(document.createElement("template"),e)}let f;return null!=(f=this.shadowRoot)?f:this.attachShadow(this.constructor.ub)};var c=a.connectedCallback;a.connectedCallback=function(){c.call(this);this.xa&&window.ShadyCSS.styleElement(this)};var d=a.fb;a.fb=function(e){this.xa||window.ShadyCSS.styleElement(this);d.call(this,
e)}}};let Ma;null!=(Ma=window).reactiveElementPolyfillSupport||(Ma.reactiveElementPolyfillSupport=La);const Na=({LitElement:a})=>{if(void 0!==window.ShadyCSS&&(!window.ShadyCSS.nativeShadow||window.ShadyCSS.ApplyShim)){a.zb=!0;a=a.prototype;var b=a.la;a.la=function(){this.eb.scope=this.localName;return b.call(this)}}};let Oa;null!=(Oa=window).litElementPolyfillSupport||(Oa.litElementPolyfillSupport=Na);/*

 Copyright 2018 Google LLC
 SPDX-License-Identifier: BSD-3-Clause
*/
function Pa(a){return a&&a.va?a.l():a}
const Qa={CONSTANT:{na(a){return a instanceof C},oa:function(a){return a instanceof C&&a.constructor===C&&a.v===ma?a.g:"type_error:Const"}},JAVASCRIPT:{na(a){return a instanceof oa},oa:function(a){return a instanceof oa&&a.constructor===oa?a.g:"type_error:SafeScript"}},HTML:{na(a){return a instanceof F},oa:a=>wa(a)},RESOURCE_URL:{na(a){return a instanceof D},oa:function(a){return qa(a)}},STRING:{na(a){return a instanceof Object},oa:Pa},STYLE:{na(a){return a instanceof ua},oa:function(a){return a instanceof
ua&&a.constructor===ua?a.g:"type_error:SafeStyle"}},URL:{na(a){return a instanceof E},oa:function(a){return a instanceof E&&a.constructor===E?a.g:"type_error:SafeUrl"}}};function Ra(a,b){return b}
const Sa={CONSTANT:Ra,JAVASCRIPT:Ra,HTML:a=>{var b={};a=a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&apos;");b.cd&&(a=a.replace(/(^|[\r\n\t ]) /g,"$1&#160;"));b.bd&&(a=a.replace(/(\r\n|\n|\r)/g,"<br>"));b.ed&&(a=a.replace(/(\t+)/g,'<span style="white-space:pre">$1</span>'));b=a;b=(a=ka())?a.createHTML(b):b;return wa(new F(b,va))},RESOURCE_URL:Ra,STRING:String,STYLE:Ra,URL:(a,b)=>{a:{for(let c=0;c<ya.length;++c){const d=ya[c];if(d instanceof
xa&&d.fc(a)){a=new E(a,sa);break a}}a=void 0}return void 0===a?b:a.toString()}};function Ta(a){return String(a).replace(/\-([a-z])/g,function(b,c){return c.toUpperCase()})};function Ua(a,b,c){if(Object.hasOwnProperty.call(Va,a)&&(a=Va[a],Object.hasOwnProperty.call(a,b)&&(a=a[b],a instanceof Array))){let e=null,f=!1;for(let h=0,k=a.length;h<k;++h){const g=a[h];var d=g.m;if(!d)return g.h;null===e&&(e={});d=Object.hasOwnProperty.call(e,d)?e[d]:e[d]=c(d);if(d===g.o)return g.h;null==d&&(f=!0)}if(f)return null}b=Wa[b];return"number"===typeof b?b:null}
const Wa={align:1,alt:1,"aria-activedescendant":10,"aria-atomic":1,"aria-autocomplete":1,"aria-busy":1,"aria-checked":1,"aria-controls":10,"aria-current":1,"aria-disabled":1,"aria-dropeffect":1,"aria-expanded":1,"aria-haspopup":1,"aria-hidden":1,"aria-invalid":1,"aria-label":1,"aria-labelledby":10,"aria-level":1,"aria-live":1,"aria-multiline":1,"aria-multiselectable":1,"aria-orientation":1,"aria-owns":10,"aria-posinset":1,"aria-pressed":1,"aria-readonly":1,"aria-relevant":1,"aria-required":1,"aria-selected":1,
"aria-setsize":1,"aria-sort":1,"aria-valuemax":1,"aria-valuemin":1,"aria-valuenow":1,"aria-valuetext":1,async:8,autocapitalize:1,autocomplete:1,autocorrect:1,autofocus:1,autoplay:1,bgcolor:1,border:1,cellpadding:1,cellspacing:1,checked:1,cite:3,"class":1,color:1,cols:1,colspan:1,contenteditable:1,controls:1,datetime:1,dir:8,disabled:1,download:1,draggable:1,enctype:1,face:1,"for":10,formenctype:1,frameborder:1,height:1,hidden:1,href:4,hreflang:1,id:10,ismap:1,itemid:1,itemprop:1,itemref:1,itemscope:1,
itemtype:1,label:1,lang:1,list:10,loading:8,loop:1,max:1,maxlength:1,media:1,min:1,minlength:1,multiple:1,muted:1,name:10,nonce:1,open:1,placeholder:1,poster:3,preload:1,rel:1,required:1,reversed:1,role:1,rows:1,rowspan:1,selected:1,shape:1,size:1,sizes:1,slot:1,span:1,spellcheck:1,src:4,srcset:11,start:1,step:1,style:5,summary:1,tabindex:1,target:8,title:1,translate:1,type:1,valign:1,value:1,width:1,wrap:1},Va={a:{href:[{h:3}]},area:{href:[{h:3}]},audio:{src:[{h:3}]},button:{formaction:[{h:3}],formmethod:[{h:1}]},
form:{action:[{h:3}],method:[{h:1}]},iframe:{srcdoc:[{h:2}]},img:{src:[{h:3}]},input:{accept:[{h:1}],formaction:[{h:3}],formmethod:[{h:1}],pattern:[{h:1}],readonly:[{h:1}],src:[{h:3}]},link:{href:[{h:3,m:"rel",o:"alternate"},{h:3,m:"rel",o:"author"},{h:3,m:"rel",o:"bookmark"},{h:3,m:"rel",o:"canonical"},{h:3,m:"rel",o:"cite"},{h:3,m:"rel",o:"help"},{h:3,m:"rel",o:"icon"},{h:3,m:"rel",o:"license"},{h:3,m:"rel",o:"next"},{h:3,m:"rel",o:"prefetch"},{h:3,m:"rel",o:"dns-prefetch"},{h:3,m:"rel",o:"prerender"},
{h:3,m:"rel",o:"preconnect"},{h:3,m:"rel",o:"preload"},{h:3,m:"rel",o:"prev"},{h:3,m:"rel",o:"search"},{h:3,m:"rel",o:"subresource"}]},script:{defer:[{h:1}]},source:{src:[{h:3}]},textarea:{readonly:[{h:1}]},video:{src:[{h:3}]}},Xa={a:1,abbr:1,address:1,applet:4,area:5,article:1,aside:1,audio:1,b:1,base:4,bdi:1,bdo:1,blockquote:1,body:1,br:5,button:1,canvas:1,caption:1,center:1,cite:1,code:1,col:5,colgroup:1,command:1,data:1,datalist:1,dd:1,del:1,details:1,dfn:1,dialog:1,div:1,dl:1,dt:1,em:1,embed:4,
fieldset:1,figcaption:1,figure:1,font:1,footer:1,form:1,frame:1,frameset:1,h1:1,h2:1,h3:1,h4:1,h5:1,h6:1,head:1,header:1,hr:5,html:1,i:1,iframe:1,img:5,input:5,ins:1,kbd:1,label:1,legend:1,lh:1,li:1,link:5,main:1,map:1,mark:1,math:4,menu:1,meta:4,meter:1,nav:1,noscript:1,object:4,ol:1,optgroup:1,option:1,output:1,p:1,param:5,picture:1,pre:1,progress:1,q:1,rb:1,rp:1,rt:1,rtc:1,ruby:1,s:1,samp:1,script:3,section:1,select:1,slot:1,small:1,source:5,span:1,strong:1,style:2,sub:1,summary:1,sup:1,svg:4,
table:1,tbody:1,td:1,template:4,textarea:6,tfoot:1,th:1,thead:1,time:1,title:6,tr:1,track:5,u:1,ul:1,"var":1,video:1,wbr:5},Ya=[{auto:!0,ltr:!0,rtl:!0},{async:!0},{eager:!0,lazy:!0},{_self:!0,_blank:!0}],Za={"*":{async:1,dir:0,loading:2,target:3}};function $a(a){var b=ab;if(!b){b=bb();const d={};for(var c in b)d[b[c]]=c;b=ab=d}c=b[a];return"string"===typeof c?c:String(a).replace(/([A-Z])/g,"-$1").toLowerCase()}function cb(a){a=String(a).toLowerCase();const b=bb()[a];return"string"===typeof b?b:Ta(a)}function db(a){a=a.toLowerCase();a=bb()[a];return"string"===typeof a?a:null}function bb(){if(!eb){const a={...fb};for(const b of gb)a[b.toLowerCase()]=b;eb=a}return eb}
const gb="aLink accessKey allowFullscreen bgColor cellPadding cellSpacing codeBase codeType contentEditable crossOrigin dateTime dirName formAction formEnctype formMethod formNoValidate formTarget frameBorder innerHTML innerText inputMode isMap longDesc marginHeight marginWidth maxLength mediaGroup minLength noHref noResize noShade noValidate noWrap nodeValue outerHTML outerText readOnly tabIndex textContent trueSpeed useMap vAlign vLink valueAsDate valueAsNumber valueType".split(" "),fb={accept_charset:"acceptCharset",
"char":"ch",charoff:"chOff",checked:"defaultChecked","class":"className","for":"htmlFor",http_equiv:"httpEquiv",muted:"defaultMuted",selected:"defaultSelected",value:"defaultValue"};let eb=null,ab=null;/*

 Copyright 2017 Google LLC
 SPDX-License-Identifier: BSD-3-Clause

*/
const hb={},ib=RegExp("^(?!(?:annotation-xml|color-profile|font-face|font-face(?:-(?:src|uri|format|name))?|missing-glyph)$)[a-z][a-z.0-9_\u00b7\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u037d\u200c\u200d\u203f-\u2040\u2070-\u218f\u2c00-\u2fef\u3001-\udfff\uf900-\ufdcf\ufdf0-\ufffd]*-[\\-a-z.0-9_\u00b7\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u037d\u200c\u200d\u203f-\u2040\u2070-\u218f\u2c00-\u2fef\u3001-\udfff\uf900-\ufdcf\ufdf0-\ufffd]*$");
function jb(a,b){const c=window.customElements;return c&&c.get(a)||!0===hb[a]?2:"HTMLUnknownElement"===b.name?1:"HTMLElement"===b.name&&ib.test(a)?3:0};/*

 Copyright 2020 Google LLC
 SPDX-License-Identifier: BSD-3-Clause
*/
function kb(a,b){switch(b){case "innerHTML":return 1===lb(a)?2:null;case "textContent":return a=lb(a),1===a||6===a?1:null;default:let c,d;return null!=(d=null==(c=mb[a.localName])?void 0:c[b])?d:null}}function lb(a){const b=a.localName,c=jb(b,a.constructor);switch(c){case 0:case 1:return nb(b,a);case 3:case 2:return 1;default:ja(c,"got an unknown element classification")}}
function nb(a,b){var c=Object.hasOwnProperty.call(Xa,a)?Xa[a]:null;return null!==c?c:Object.hasOwnProperty.call(ob,a)&&b instanceof SVGElement?ob[a]:null}const ob={text:1},mb={audio:{currentTime:1,srcObject:1},video:{currentTime:1,srcObject:1}};const pb=/(?!,)([^\t\n\f\r ]+)(?:[\t\n\f\r ]+([.0-9+\-]+[a-z]?))?/gi,qb=/[\t\n\f\r ]+/,rb=/[\t\n\f\r ,]+/g;function sb(a){return(a=a.split(qb,2))?{url:a[0],metadata:a[1]}:null}function tb(a){let b=String(a.url).replace(rb,encodeURIComponent);if(a=a.metadata){rb.lastIndex=0;if(rb.test(a))return null;b+=" "+a}return b}const ub=(a,b,c)=>c,I={};
function vb(a,b,c){const d=[,{aa(e,f,h){return h},ba:void 0,da:void 0,ea:void 0},{aa:void 0,ba:void 0,da:void 0,ea:"HTML"}];d[3]={aa:void 0,ba:void 0,da:wb,ea:"URL"};d[4]={aa:void 0,ba:void 0,da:wb,ea:"RESOURCE_URL"};d[5]={aa:void 0,ba:void 0,da:J,ea:"STYLE"};d[7]={aa:void 0,ba:void 0,da:xb,ea:"JAVASCRIPT"};d[8]={aa:void 0,ba(e,f,h){h=String(h).toLowerCase();a:{let k=null;(e=Za[e])&&(k=e[f]);if("number"!==typeof k&&((e=Za["*"])&&(k=e[f]),"number"!==typeof k)){f=!1;break a}f=!0===Ya[k][String(h).toLowerCase()]}return f?
h:J},da:J,ea:void 0};d[9]={aa:void 0,ba:void 0,da:J,ea:"CONSTANT"};d[10]={aa:void 0,ba(e,f,h){return a.test(h)?h:J},da:J,ea:"CONSTANT"};d[11]={aa(e,f,h,k){if("string"===typeof h)var g=(g=h.match(pb))?g.map(sb).filter(Boolean):[];else if(Array.isArray(h))g=h;else return wb;var l=g;g=[];var u=[];const q={};if(Array.isArray(l))for(let w=0,n=l.length;w<n;++w){const p=l[w],t=p&&p.url;if(t){const m=b(t,"URL",q);if(m){const r=m!==q;(r?g:u).push({url:r?m:t,metadata:p.metadata})}}}else u.push(l);l=u.length?
JSON.stringify(u):null;u=I;if(g.length){if(!Array.isArray(g))throw Error();u=g.map(tb).filter(Boolean).join(" , ")||I}l&&c&&c(!0,`Failed to sanitize attribute value of <${e}>: <${e} ${f}="${h}">: ${l}`,k);return u===I?wb:u},ba:void 0,da:void 0,ea:void 0};return d}
const {xb:J,wb:xb,yb:wb}=(()=>{var a=(()=>{const d={createHTML:()=>"zClosurez",createScript:()=>" /*zClosurez*/ ",createScriptURL:()=>"about:invalid#zClosurez"};return"undefined"!==typeof trustedTypes?trustedTypes.createPolicy("polymer_resin",d):d})();const b=a.createHTML(""),c=a.createScript("");a=a.createScriptURL("");return{xb:b,wb:c,yb:a}})();/*

 Copyright 2019 Google LLC
 SPDX-License-Identifier: BSD-3-Clause
*/
var K=function(a){function b(g){const l=g.localName;if(!g.getAttribute("is")&&2===jb(l,g.constructor))return k;(g=h[l])||(g=h[l]=document.createElement(l));return g}let c=a.reportHandler||void 0;const d=a.safeTypesBridge||ub;let e=/^$/;if(a=a.allowedIdentifierPrefixes)for(const g of a)e=new RegExp(e.source+"|^"+String(g).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"));c&&c(!1,"initResin",null);const f=vb(e,d,c),h={},k=document.createElement("polyresinuncustomized");return function(g,
l,u){var q=g.nodeType;if(q!==Node.ELEMENT_NODE){if(q===Node.TEXT_NODE){l=g.parentElement;u=!l;if(l&&l.nodeType===Node.ELEMENT_NODE){q=l.localName;var w=jb(q,l.constructor);switch(w){case 0:case 1:l=nb(q,l);u=1===l||6===l;break;case 3:case 2:u=!0;break;default:ja(w,"got an unknown element classification")}}if(u)return m=>""+d(m,"STRING",m)}return m=>{if(!m&&m!==document.all)return m;c&&c(!0,`Failed to sanitize ${g.parentElement&&g.parentElement.nodeName} #text node to value ${m}`,g.parentElement);
return J}}const n=g.localName;q=b(g);let p=null;switch(u){case "attribute":if(cb(l)in q)break;return m=>m;case "property":if(l in q){p=kb(q,l);break}if((w=db(l))&&w in q)break;return m=>m;default:ja(u,"got an unknown resin type, expected either 'property' or 'attribute'")}const t="attribute"===u?l.toLowerCase():$a(l);p||(p=Ua(n,t,m=>{const r=g.getAttribute(m);return!r||/[\[\{]/.test(m)?null:r}));return m=>{var r=I;let y=null;if(!m&&m!==document.all)return m;if(null!=p){const v=f[p],U=v.ea;y=v.da;
U&&(r=d(m,U,I));r===I&&(v.ba?(r=String(d(m,"STRING",m)),r=v.ba(n,t,r)):v.aa&&(r=v.aa(n,t,m,g)),r===y&&(r=I))}r===I&&(r=y||J,c&&c(!0,`Failed to sanitize attribute of <${n}>: <${n} ${t}="${m}">`,g));return r}}}({allowedIdentifierPrefixes:[""],reportHandler:function(){},safeTypesBridge:(a,b,c)=>{var d=Qa[b];return d.na(a)&&(d=d.oa(a,c),d!==c)?d:(0,Sa[b])(String(Pa(a)),c)}});const L=window;let yb,zb,Ab;
const M=(null==(yb=L.ShadyDOM)?0:yb.inUse)&&(!0===(null==(zb=L.ShadyDOM)?void 0:zb.noPatch)||"on-demand"===(null==(Ab=L.ShadyDOM)?void 0:Ab.noPatch))?L.ShadyDOM.wrap:a=>a,N=L.trustedTypes,Bb=N?N.createPolicy("lit-html",{createHTML:a=>a}):void 0,Cb=a=>a,Db=()=>Cb,Eb=new Map,O=`lit$${String(Math.random()).slice(9)}$`,Fb="?"+O,Gb=`<${Fb}>`,P=document,Q=a=>null===a||"object"!=typeof a&&"function"!=typeof a||Ka(a),Hb=Array.isArray,R=/<(?:(!--|\/[^a-zA-Z])|(\/?[a-zA-Z][^>\s]*)|(\/?$))/g,Ib=/--\x3e/g,Jb=
/>/g,S=RegExp(">|[ \t\n\f\r](?:([^\\s\"'>=/]+)([ \t\n\f\r]*=[ \t\n\f\r]*(?:[^ \t\n\f\r\"'`<>=]|(\"|')|))|$)","g"),Kb=/'/g,Lb=/"/g,Mb=/^(?:script|style|textarea|title)$/i;var Nb=(a,...b)=>({_$litType$:1,fa:a,values:b}),T=Symbol.for("lit-noChange"),V=Symbol.for("lit-nothing");const Ob=new WeakMap,W=P.createTreeWalker(P,129,null,!1);
var Pb=class{constructor({fa:a,_$litType$:b},c){this.parts=[];let d=0,e=0;const f=a.length-1,h=this.parts;var k=a.length-1,g=[];let l=2===b?"<svg>":"",u,q=R;for(let t=0;t<k;t++){const m=a[t];let r=-1,y;var w=0;let v;for(;w<m.length;){q.lastIndex=w;v=q.exec(m);if(null===v)break;w=q.lastIndex;if(q===R)"!--"===v[1]?q=Ib:void 0!==v[1]?q=Jb:void 0!==v[2]?(Mb.test(v[2])&&(u=new RegExp(`</${v[2]}`,"g")),q=S):void 0!==v[3]&&(q=S);else if(q===S)if(">"===v[0]){let U;q=null!=(U=u)?U:R;r=-1}else void 0===v[1]?
r=-2:(r=q.lastIndex-v[2].length,y=v[1],q=void 0===v[3]?S:'"'===v[3]?Lb:Kb);else q===Lb||q===Kb?q=S:q===Ib||q===Jb?q=R:(q=S,u=void 0)}w=q===S&&a[t+1].startsWith("/>")?" ":"";l+=q===R?m+Gb:0<=r?(g.push(y),m.slice(0,r)+"$lit$"+m.slice(r))+O+w:m+O+(-2===r?(g.push(void 0),t):w)}k=l+(a[k]||"<?>")+(2===b?"</svg>":"");if(!Array.isArray(a)||!a.hasOwnProperty("raw"))throw Error("invalid template strings array");a=[void 0!==Bb?Bb.createHTML(k):k,g];const [n,p]=a;this.ua=Pb.createElement(n,c);W.currentNode=this.ua.content;
2===b&&(b=this.ua.content,c=b.firstChild,c.remove(),b.append(...c.childNodes));for(;null!==(b=W.nextNode())&&h.length<f;){if(1===b.nodeType){if(b.hasAttributes()){c=[];for(const t of b.getAttributeNames())if(t.endsWith("$lit$")||t.startsWith(O))g=p[e++],c.push(t),void 0!==g?(a=b.getAttribute(g.toLowerCase()+"$lit$").split(O),g=/([.?@])?(.*)/.exec(g),h.push({type:1,index:d,name:g[2],fa:a,ac:"."===g[1]?Qb:"?"===g[1]?Rb:"@"===g[1]?Sb:Tb})):h.push({type:6,index:d});for(const t of c)b.removeAttribute(t)}if(Mb.test(b.tagName)&&
(c=b.textContent.split(O),a=c.length-1,0<a)){b.textContent=N?N.emptyScript:"";for(g=0;g<a;g++)b.append(c[g],P.createComment("")),W.nextNode(),h.push({type:2,index:++d});b.append(c[a],P.createComment(""))}}else if(8===b.nodeType)if(b.data===Fb)h.push({type:2,index:d});else for(c=-1;-1!==(c=b.data.indexOf(O,c+1));)h.push({type:7,index:d}),c+=O.length-1;d++}}static createElement(a){const b=P.createElement("template");b.innerHTML=a;return b}};
function X(a,b,c=a,d){if(b===T)return b;var e;let f=void 0!==d?null==(e=c.g)?void 0:e[d]:c.za;e=Q(b)?void 0:b._$litDirective$;let h;if((null==(h=f)?void 0:h.constructor)!==e){let k,g;null==(k=f)||null==(g=k._$notifyDirectiveConnectionChanged)||g.call(k,!1);void 0===e?f=void 0:(f=new e(a),f.kc(a,c,d));if(void 0!==d){let l;(null!=(l=c.g)?l:c.g=[])[d]=f}else c.za=f}void 0!==f&&(b=X(a,f.lc(a,b.values),f,d));return b}
class Ub{constructor(a,b){this.g=[];this.ia=void 0;this.gb=a;this.l=b}get parentNode(){return this.l.parentNode}get ka(){return this.l.ka}ca(a){const {ua:{content:b},parts:c}=this.gb;var d;const e=(null!=(d=null==a?void 0:a.oc)?d:P).importNode(b,!0);W.currentNode=e;d=W.nextNode();let f=0,h=0,k=c[0];for(;void 0!==k;){if(f===k.index){let l;2===k.type?l=new Vb(d,d.nextSibling,this,a):1===k.type?l=new k.ac(d,k.name,k.fa,this,a):6===k.type&&(l=new Wb(d,this,a));this.g.push(l);k=c[++h]}let g;f!==(null==
(g=k)?void 0:g.index)&&(d=W.nextNode(),f++)}return e}v(a){let b=0;for(const c of this.g)void 0!==c&&(void 0!==c.fa?(c.ga(a,c,b),b+=c.fa.length-2):c.ga(a[b])),b++}}function Xb(a,b){if(void 0===a.l){a.ra=b;let c;null==(c=a.ya)||c.call(a,b)}}
var Vb=class{constructor(a,b,c,d){this.type=2;this.j=V;this.ia=void 0;this.ha=a;this.pa=b;this.l=c;this.options=d;let e;this.ra=null!=(e=null==d?void 0:d.isConnected)?e:!0;this.g=void 0}get ka(){let a,b;return null!=(b=null==(a=this.l)?void 0:a.ka)?b:this.ra}get parentNode(){let a=M(this.ha).parentNode;const b=this.l;void 0!==b&&11===a.nodeType&&(a=b.parentNode);return a}ga(a,b=this){a=X(this,a,b);Q(a)?a===V||null==a||""===a?(this.j!==V&&this.v(),this.j=V):a!==this.j&&a!==T&&this.sa(a):void 0!==a._$litType$?
this.kb(a):void 0!==a.nodeType?this.ca(a):Hb(a)||"function"===typeof(null==a?void 0:a[Symbol.iterator])?this.bb(a):this.sa(a)}ja(a,b=this.pa){return M(M(this.ha).parentNode).insertBefore(a,b)}ca(a){if(this.j!==a){this.v();if(K!==Db){let b;const c=null==(b=this.ha.parentNode)?void 0:b.nodeName;if("STYLE"===c||"SCRIPT"===c)throw Error("Forbidden");}this.j=this.ja(a)}}sa(a){if(this.j!==V&&Q(this.j)){var b=M(this.ha).nextSibling;void 0===this.g&&(this.g=K(b,"data","property"));a=this.g(a);b.data=a}else b=
document.createTextNode(""),this.ca(b),void 0===this.g&&(this.g=K(b,"data","property")),a=this.g(a),b.data=a;this.j=a}kb(a){const {values:b,_$litType$:c}=a;a="number"===typeof c?this.nb(a):(void 0===c.ua&&(c.ua=Pb.createElement(c.pc,this.options)),c);var d;(null==(d=this.j)?void 0:d.gb)===a?this.j.v(b):(d=new Ub(a,this),a=d.ca(this.options),d.v(b),this.ca(a),this.j=d)}nb(a){const b=a.fa;let c=Ob.get(b);if(void 0===c){const d=b.join("\x00");c=Eb.get(d);void 0===c&&(c=new Pb(a),Eb.set(d,c));Ob.set(b,
c)}return c}bb(a){Hb(this.j)||(this.j=[],this.v());const b=this.j;let c=0,d;for(const e of a)c===b.length?b.push(d=new Vb(this.ja(P.createComment("")),this.ja(P.createComment("")),this,this.options)):d=b[c],d.ga(e),c++;c<b.length&&(this.v(d&&M(d.pa).nextSibling,c),b.length=c)}v(a=M(this.ha).nextSibling,b){let c;for(null==(c=this.ya)||c.call(this,!1,!0,b);a&&a!==this.pa;)b=M(a).nextSibling,M(a).remove(),a=b}},Tb=class{constructor(a,b,c,d,e){this.type=1;this.j=V;this.ia=void 0;this.element=a;this.name=
b;this.l=d;this.options=e;2<c.length||""!==c[0]||""!==c[1]?(this.j=Array(c.length-1).fill(new String),this.fa=c):this.j=V;this.qa=void 0}get tagName(){return this.element.tagName}get ka(){return this.l.ka}ga(a,b=this,c,d){const e=this.fa;let f=!1;if(void 0===e){if(a=X(this,a,b,0),f=!Q(a)||a!==this.j&&a!==T)this.j=a}else{const h=a;a=e[0];let k,g;for(k=0;k<e.length-1;k++){g=X(this,h[c+k],b,k);g===T&&(g=this.j[k]);f||(f=!Q(g)||g!==this.j[k]);if(g===V)a=V;else if(a!==V){let l;a+=(null!=(l=g)?l:"")+e[k+
1]}this.j[k]=g}}f&&!d&&this.hb(a)}hb(a){if(a===V)M(this.element).removeAttribute(this.name);else{void 0===this.qa&&(this.qa=K(this.element,this.name,"attribute"));let b;a=this.qa(null!=(b=a)?b:"");let c;M(this.element).setAttribute(this.name,null!=(c=a)?c:"")}}},Qb=class extends Tb{constructor(){super(...arguments);this.type=3}hb(a){void 0===this.qa&&(this.qa=K(this.element,this.name,"property"));a=this.qa(a);this.element[this.name]=a===V?void 0:a}};const Yb=N?N.emptyScript:"";
var Rb=class extends Tb{constructor(){super(...arguments);this.type=4}hb(a){a&&a!==V?M(this.element).setAttribute(this.name,Yb):M(this.element).removeAttribute(this.name)}},Sb=class extends Tb{constructor(a,b,c,d,e){super(a,b,c,d,e);this.type=5}ga(a,b=this){var c;a=null!=(c=X(this,a,b,0))?c:V;if(a!==T){b=this.j;c=a===V&&b!==V||a.capture!==b.capture||a.once!==b.once||a.passive!==b.passive;var d=a!==V&&(b===V||c);c&&this.element.removeEventListener(this.name,this,b);d&&this.element.addEventListener(this.name,
this,a);this.j=a}}handleEvent(a){if("function"===typeof this.j){let b,c;this.j.call(null!=(c=null==(b=this.options)?void 0:b.host)?c:this.element,a)}else this.j.handleEvent(a)}},Wb=class{constructor(a,b,c){this.element=a;this.type=6;this.ia=void 0;this.l=b;this.options=c}get ka(){return this.l.ka}ga(a){X(this,a)}};let Zb;null==(Zb=window.litHtmlPolyfillSupport)||Zb(Pb,Vb);let $b;(null!=($b=L.litHtmlVersions)?$b:L.litHtmlVersions=[]).push("2.4.0");const ac=window;var bc=ac.ShadowRoot&&(void 0===ac.ShadyCSS||ac.ShadyCSS.nativeShadow)&&"adoptedStyleSheets"in Document.prototype&&"replace"in CSSStyleSheet.prototype;const cc=Symbol();
var dc=class{constructor(a){this._$cssResult$=!0;if(cc!==cc)throw Error("CSSResult is not constructable. Use `unsafeCSS` or `css` instead.");this.cssText=a;this.g=void 0}get styleSheet(){let a=this.l;bc&&void 0===a&&void 0===a&&(this.l=a=new CSSStyleSheet).replaceSync(this.cssText);return a}toString(){return this.cssText}},ec=(a,b)=>{bc?a.adoptedStyleSheets=b.map(c=>c instanceof CSSStyleSheet?c:c.styleSheet):b.forEach(c=>{const d=document.createElement("style"),e=ac.litNonce;void 0!==e&&d.setAttribute("nonce",
e);d.textContent=c.cssText;a.appendChild(d)})},fc=bc?a=>a:a=>{if(a instanceof CSSStyleSheet){let b="";for(const c of a.cssRules)b+=c.cssText;a=new dc("string"===typeof b?b:String(b))}return a};/*

 Copyright 2016 Google LLC
 SPDX-License-Identifier: BSD-3-Clause
*/
(function(){if(ia&&!HTMLElement.es5Shimmed&&void 0!==x.Reflect&&void 0!==x.customElements&&!x.customElements.polyfillWrapFlushCallback){var a=HTMLElement;x.HTMLElement=function(){return Reflect.construct(a,[],this.constructor)};HTMLElement.prototype=a.prototype;HTMLElement.prototype.constructor=HTMLElement;HTMLElement.es5Shimmed=!0;Object.setPrototypeOf(HTMLElement,a)}})();const gc=window,hc=gc.trustedTypes,ic=hc?hc.emptyScript:"",jc=gc.reactiveElementPolyfillSupport;var kc={vb(a,b){switch(b){case Boolean:a=a?ic:null;break;case Object:case Array:a=null==a?a:JSON.stringify(a)}return a},lb(a,b){let c=a;switch(b){case Boolean:c=null!==a;break;case Number:c=null===a?null:Number(a);break;case Object:case Array:try{c=JSON.parse(a)}catch(d){c=null}}return c}},lc=(a,b)=>b!==a&&(b===b||a===a);const mc={qb:!0,type:String,ta:kc,tb:!1,dc:lc};
function Ca(a,b,c=mc){c.state&&(c.qb=!1);a.finalize();a.ma.set(b,c);c.ad||a.prototype.hasOwnProperty(b)||(c=nc(b,"symbol"===typeof b?Symbol():`__${b}`,c),void 0!==c&&Object.defineProperty(a.prototype,b,c))}function nc(a,b,c){return{get(){return this[b]},set(d){const e=this[a];this[b]=d;oc(this,a,e,c)},configurable:!0,enumerable:!0}}
function oc(a,b,c,d){let e=!0;void 0!==b&&(d=d||a.constructor.ma.get(b)||mc,(d.dc||lc)(a[b],c)?(a.ia.has(b)||a.ia.set(b,c),!0===d.tb&&a.l!==b&&(void 0===a.g&&(a.g=new Map),a.g.set(b,d))):e=!1);!a.v&&e&&(a.za=a.bc())}function pc(a){if(a.v){a.ca&&(a.ca.forEach((d,e)=>a[e]=d),a.ca=void 0);var b=!1,c=a.ia;try{b=!0;let d;null==(d=a.sa)||d.forEach(e=>{let f;return null==(f=e.sc)?void 0:f.call(e)});a.update(c)}catch(d){throw b=!1,a.ya(),d;}b&&a.fb(c)}}
var Y=class extends HTMLElement{constructor(){super();this.ca=new Map;this.xa=this.v=!1;this.l=null;this.hc()}static get observedAttributes(){this.finalize();const a=[];this.ma.forEach((b,c)=>{b=this.ob(c,b);void 0!==b&&(this.pb.set(b,c),a.push(b))});return a}static finalize(){if(this.hasOwnProperty("finalized"))return!1;this.finalized=!0;var a=Object.getPrototypeOf(this);a.finalize();void 0!==a.ib&&(this.ib=[...a.ib]);this.ma=new Map(a.ma);this.pb=new Map;if(this.hasOwnProperty("properties")){a=
this.properties;const c=[...Object.getOwnPropertyNames(a),...Object.getOwnPropertySymbols(a)];for(var b of c)Ca(this,b,a[b])}a=this.styles;b=[];if(Array.isArray(a)){a=new Set(a.flat(Infinity).reverse());for(const c of a)b.unshift(fc(c))}else void 0!==a&&b.push(fc(a));this.jb=b;return!0}static ob(a,b){b=b.qb;return!1===b?void 0:"string"===typeof b?b:"string"===typeof a?a.toLowerCase():void 0}hc(){this.za=new Promise(b=>this.bb=b);this.ia=new Map;this.ec();oc(this);let a;null==(a=this.constructor.ib)||
a.forEach(b=>b(this))}ec(){this.constructor.ma.forEach((a,b)=>{this.hasOwnProperty(b)&&(this.ca.set(b,this[b]),delete this[b])})}la(){let a;const b=null!=(a=this.shadowRoot)?a:this.attachShadow(this.constructor.ub);ec(b,this.constructor.jb);return b}connectedCallback(){void 0===this.ja&&(this.ja=this.la());this.bb(!0);let a;null==(a=this.sa)||a.forEach(b=>{let c;return null==(c=b.qc)?void 0:c.call(b)})}bb(){}disconnectedCallback(){let a;null==(a=this.sa)||a.forEach(b=>{let c;return null==(c=b.rc)?
void 0:c.call(b)})}attributeChangedCallback(a,b,c){this.kb(a,c)}cc(a,b,c=mc){const d=this.constructor.ob(a,c);if(void 0!==d&&!0===c.tb){let e;const f=(void 0!==(null==(e=c.ta)?void 0:e.vb)?c.ta:kc).vb(b,c.type);this.l=a;null==f?this.removeAttribute(d):this.setAttribute(d,f);this.l=null}}kb(a,b){var c=this.constructor;a=c.pb.get(a);if(void 0!==a&&this.l!==a){c=c.ma.get(a)||mc;let d;const e="function"===typeof c.ta?{lb:c.ta}:void 0!==(null==(d=c.ta)?void 0:d.lb)?c.ta:kc;this.l=a;this[a]=e.lb(b,c.type);
this.l=null}}async bc(){this.v=!0;try{await this.za}catch(b){this.wc||Promise.reject(b)}const a=pc(this);null!=a&&await a;return!this.v}fb(a){let b;null==(b=this.sa)||b.forEach(c=>{let d;return null==(d=c.tc)?void 0:d.call(c)});this.xa||(this.xa=!0);this.updated(a)}ya(){this.ia=new Map;this.v=!1}update(){void 0!==this.g&&(this.g.forEach((a,b)=>this.cc(b,this[b],a)),this.g=void 0);this.ya()}updated(){}};Y.finalized=!0;Y.ma=new Map;Y.jb=[];Y.ub={mode:"open"};null==jc||jc({ReactiveElement:Y});let qc;
(null!=(qc=gc.reactiveElementVersions)?qc:gc.reactiveElementVersions=[]).push("1.4.2");var rc=class extends Y{constructor(){super(...arguments);this.eb={host:this};this.ra=void 0}la(){const a=super.la();let b;null!=(b=this.eb).mb||(b.mb=a.firstChild);return a}update(a){const b=this.render();this.xa||(this.eb.isConnected=this.isConnected);super.update(a);a=this.ja;var c=this.eb,d;const e=null!=(d=null==c?void 0:c.mb)?d:a;d=e._$litPart$;if(void 0===d){let f;d=null!=(f=null==c?void 0:c.mb)?f:null;e._$litPart$=d=new Vb(a.insertBefore(P.createComment(""),d),d,void 0,null!=c?c:{})}d.ga(b);
this.ra=d}connectedCallback(){super.connectedCallback();let a;null==(a=this.ra)||Xb(a,!0)}disconnectedCallback(){super.disconnectedCallback();let a;null==(a=this.ra)||Xb(a,!1)}render(){return T}};rc.finalized=!0;rc._$litElement$=!0;let sc;null==(sc=window.litElementPolyfillSupport)||sc({LitElement:rc});let tc,uc;(null!=(uc=(tc=window).litElementVersions)?uc:tc.litElementVersions=[]).push("3.2.2");function vc(a){if(!document.head.querySelector("#codemirror")){var b=document.createElement("script");b.id="codemirror";b.crossOrigin="anonymous";var c,d;a=null!=(d=null==(c=a.plugin)?void 0:c.url())?d:"";c=za`https://cdn.googlesource.com/${`${a}`.replace("https://cdn.googlesource.com/","")}static/codemirror_element.js`;b.src=qa(c);var e;let f;(e=(c=null==(f=(e=(b.ownerDocument&&b.ownerDocument.defaultView||window).document).querySelector)?void 0:f.call(e,"script[nonce]"))?c.nonce||c.getAttribute("nonce")||
"":"")&&b.setAttribute("nonce",e);document.head.appendChild(b)}}
let Z=class extends rc{render(){if(window.customElements.get("codemirror-element")){var a=this.lineNum;let b;const c={value:null!=(b=this.fileContent)?b:"",viewportMargin:Infinity};if(this.prefs){c.mc=this.prefs.nc;c.cursorHeight=.85;c.indentUnit=this.prefs.uc;c.indentWithTabs=this.prefs.vc;c.lineNumbers=!0;c.lineWrapping=this.prefs.line_wrapping;c.matchBrackets=this.prefs.yc;let d;c.mode=this.prefs.syntax_highlighting?null!=(d=this.fileType)?d:"":"";c.hd=this.prefs.show_tabs;c.jd=this.prefs.show_whitespace_errors;
c.tabSize=this.prefs.tab_size;c.gd=[{column:this.prefs.line_length}];let e;if(null==(e=this.fileContent)?0:e.includes("\r\n"))c.xc="\r\n"}return Nb`
      <codemirror-element
        id="codemirror"
        .lineNum=${a}
        .params=${c}>
      </codemirror-element>
    `}}connectedCallback(){super.connectedCallback();vc(this);window.customElements.whenDefined("codemirror-element").then(()=>{oc(this)})}};z([H({type:String}),A(String)],Z.prototype,"fileContent",void 0);z([H({type:String}),A(String)],Z.prototype,"fileType",void 0);z([H({type:Number}),A(Number)],Z.prototype,"lineNum",void 0);z([H({type:Object}),A(Object)],Z.prototype,"prefs",void 0);z([H({type:Object}),A(Object)],Z.prototype,"plugin",void 0);
z([function(a,b){return Ba({wa:c=>{const d={get(){let e,f;return null!=(f=null==(e=this.ja)?void 0:e.querySelector(a))?f:null},enumerable:!0,configurable:!0};if(b){const e="symbol"===typeof c?Symbol():`__${c}`;d.get=function(){if(void 0===this[e]){let f,h;this[e]=null!=(h=null==(f=this.ja)?void 0:f.querySelector(a))?h:null}return this[e]}}return d}})}("#codemirror"),A(Object)],Z.prototype,"zc",void 0);
Z=z([(a=>b=>{"function"===typeof b?customElements.define(a,b):b=Aa(a,b);return b})("gr-editor")],Z);window.Gerrit.install(a=>{a.registerCustomComponent("editor","gr-editor",{replace:!0})});})();
//# sourceMappingURL=codemirror_editor.js.sourcemap
