(function(){'use strict';var aa=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};function ba(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ca=ba(this);
function da(a,b){if(b)a:{var c=ca;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&aa(c,a,{configurable:!0,writable:!0,value:b})}}da("globalThis",function(a){return a||ca});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var q=this||self;function ea(a,b,c,d){var e=arguments.length,f=e<3?b:d===null?d=Object.getOwnPropertyDescriptor(b,c):d,g;if(Reflect&&typeof Reflect==="object"&&typeof Reflect.decorate==="function")f=Reflect.decorate(a,b,c,d);else for(var h=a.length-1;h>=0;h--)if(g=a[h])f=(e<3?g(f):e>3?g(b,c,f):g(b,c))||f;e>3&&f&&Object.defineProperty(b,c,f)};/*

 Copyright 2021 Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
class fa{constructor(){this.id="buganizer";this.name="Buganizer";this.icon="bug_report";this.placeholder="b/...";this.regex=/(?:^|\s)(?:https:\/\/(?:b|buganizer)\.corp\.google\.com\/issues\/|b\/)([1-9]\d*)(?:\/.*)?/}parse(a){var b=a.match(this.regex);if(b){var c;b=(c=b[1])!=null?c:void 0;return{type_id:this.id,identifier:b,link:a,title:b?`b/${b}`:""}}}}
class ha{constructor(){this.id="codesearch";this.name="Code Search";this.icon="search";this.placeholder="cs/...";this.regex=/(?:^|\s)(?:https:\/\/source\.corp\.google\.com\/piper\/\/\/depot\/|cs\/)([\w\/\.\-]+)(?:\?.*)?/}parse(a){var b=a.match(this.regex);if(b){var c;b=(c=b[1])!=null?c:void 0;return{type_id:this.id,identifier:b,link:a,title:b?`${b}`:""}}}}
class ia{constructor(){this.id="critique_cl";this.name="Critique CL";this.icon="check_circle";this.placeholder="cl/...";this.regex=/(?:^|\s)(?:https:\/\/critique(?:-staging)?\.corp\.google\.com\/)?cl\/([1-9]\d*)(?:\/.*)?/}parse(a){var b=a.match(this.regex);if(b){var c;b=(c=b[1])!=null?c:void 0;return{type_id:this.id,identifier:b,link:a,title:b?`cl/${b}`:""}}}}
class ja{constructor(){this.name=this.id="g3doc";this.icon="history_edu";this.placeholder="g3doc/...";this.regex=/(?:^|\s)(?:https:\/\/(?:g3doc|engdoc)\.corp\.google\.com\/|(?:g3doc|engdoc)\/)([\w\/\.\-]+\.md)(\?[\w\/\.\-=]+)?(#.*)?/}parse(a){const b=a.match(this.regex);if(b){var c=b[1];if(c){var d=b[3]||"",e=c.split("/");return{type_id:this.id,identifier:`${c}${b[2]||""}${d}`,link:a,title:e[e.length-1]+d,tooltip:a}}}}}
class ka{constructor(){this.id="gdoc";this.name="Google Doc";this.icon="docs";this.placeholder="doc/...";this.regex=/(?:^|\s)(?:https:\/\/docs\.google\.com\/document\/d\/|doc\/)([\w\.\-]+)(\/edit)?(?:\?.*)?/}parse(a){var b=a.match(this.regex);if(b){var c;b=(c=b[1])!=null?c:void 0;return{type_id:this.id,identifier:b,link:a,title:b?`${b}`:""}}}}
var ma=class{constructor(a){this.plugin=a}chat(a,b){const c=a.change;if(c.current_revision){var d=`/changes/${c._number}/revisions/${c.current_revision}/`+"chat?trace=issue/437944720";a={action:1,user_question:a.prompt,conversation_id:a.conversation_id,turn_index:a.turn_index,regeneration_index:a.regeneration_index,client_data:a.client_data,model_name:a.model_name,files:la(c,a.files)};this.plugin.restApi().post(d,a).then(e=>{console.log("asdf chat response",JSON.stringify(e));b.emitResponse(e);b.done()}).catch(e=>
{b.emitError(`Unknown error: ${e}`);b.done()})}else b.emitError("Change does not have current_revision."),b.done()}listChatConversations(a){a=`/changes/${a._number}/conversations?trace=issue/437944720`;return this.plugin.restApi().get(a).then(b=>{console.log("asdf listChatConversations",JSON.stringify(b));console.log("asdf listChatConversations typeof res",typeof b);console.log("asdf listChatConversations typeof res.conversations",typeof b.conversations);console.log("asdf listChatConversations res.conversations",
JSON.stringify(b.conversations));console.log("asdf listChatConversations Object.keys",Object.keys(b!=null?b:{}));return b.conversations})}getChatConversation(a,b){a=`/changes/${a._number}/conversations/${b}?trace=issue/437944720`;return this.plugin.restApi().get(a).then(c=>{console.log("asdf getChatConversation",JSON.stringify(c));return c.turns})}getModels(a){a=`/changes/${a._number}/chat_get_parameters?trace=issue/437944720`;return this.plugin.restApi().post(a).then(b=>{console.log("asdf getModels",
JSON.stringify(b));return{...b,documentation_url:"http://go/gob/users/ai-features",citation_url:"https://support.google.com/legal/answer/13505487",privacy_url:"https://goto.google.com/code-ai-policy"}})}getActions(){return Promise.resolve({actions:[{id:"freeform",display_text:"Free form chat"},{id:"summarize",display_text:"Summarize",initial_user_prompt:"Summarize the change",icon:"summarize",enable_splash_page_card:!0,enable_send_without_input:!0}],default_action_id:"freeform"})}getContextItemTypes(){return Promise.resolve([new fa,
new ha,new ia,new ja,new ka])}};function la(a,b){var c;let d,e;a=(a==null?0:a.revisions)&&(a==null?0:a.current_revision)?a.revisions[a.current_revision]:void 0;a=a==null?void 0:(c=a.commit)==null?void 0:(d=c.parents)==null?void 0:(e=d[0])==null?void 0:e.commit;if(!b||!a)return[];c=[];for(const f of b){a:switch(f.status){case "A":b=1;break a;case "D":b=2;break a;default:b=3}c.push({path:f.path,operation:b,base_file:{base_commit:a}})}return c};/*

 Copyright 2023 Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
function na(a){if(a===void 0)return"ERROR";switch(a){case 1:case 21:return"OK";case 0:case 2:return"NO_SUGGESTION";case 7:return"FILE_TOO_LARGE";case 8:return"INVALID_RANGE";case 9:return"UNSUPPORTED_FILE_TYPE";case 15:return"USER_QUOTA_EXCEEDED";case 20:return"OK_LOW_CONFIDENCE";default:return"ERROR"}};/*

 Copyright 2016 Google LLC
 SPDX-License-Identifier: BSD-3-Clause
*/
const oa=!!/^\s*class\s*\{\s*\}\s*$/.test(class{}.toString())||HTMLElement.es5Shimmed||q.Reflect===void 0||q.customElements===void 0||q.customElements.polyfillWrapFlushCallback||!1;let u;var pa=()=>{function a(){return c.construct(b,[],this.constructor)}const b=HTMLElement;if(oa)return b;if(u!==void 0)return u;const c=q.Reflect;a.prototype=b.prototype;a.prototype.constructor=a;a.es5Shimmed=!0;Object.setPrototypeOf(a,b);return u=a};let qa=!1;/*

 Copyright 2019 Google LLC
 SPDX-License-Identifier: BSD-3-Clause
*/
var y=q.ShadowRoot&&(q.ShadyCSS===void 0||q.ShadyCSS.nativeShadow)&&"adoptedStyleSheets"in Document.prototype&&"replace"in CSSStyleSheet.prototype;const ra=Symbol(),sa=new WeakMap;
var ta=class{constructor(a,b){this._$cssResult$=!0;if(ra!==ra)throw Error("CSSResult is not constructable. Use `unsafeCSS` or `css` instead.");this.cssText=a;this.g=b}get styleSheet(){let a=this.i;const b=this.g;if(y&&a===void 0){const c=b!==void 0&&b.length===1;c&&(a=sa.get(b));a===void 0&&((this.i=a=new CSSStyleSheet).replaceSync(this.cssText),c&&sa.set(b,a))}return a}toString(){return this.cssText}},ua=(a,...b)=>function(){const c=a.length===1?a[0]:b.reduce((d,e,f)=>{if(e._$cssResult$===!0)e=e.cssText;
else if(typeof e!=="number")throw Error("Value passed to 'css' function must be a 'css' function result: "+`${e}. Use 'unsafeCSS' to pass non-literal values, but take care `+"to ensure page security.");return d+e+a[f+1]},a[0]);return new ta(c,a)}(),va=(a,b)=>{if(y)a.adoptedStyleSheets=b.map(c=>c instanceof CSSStyleSheet?c:c.styleSheet);else for(const c of b){b=document.createElement("style");const d=q.litNonce;d!==void 0&&b.setAttribute("nonce",d);b.textContent=c.cssText;a.appendChild(b)}},wa=y?a=>
a:a=>{if(a instanceof CSSStyleSheet){let b="";for(const c of a.cssRules)b+=c.cssText;a=new ta(typeof b==="string"?b:String(b))}return a};/*

 Copyright 2017 Google LLC
 SPDX-License-Identifier: BSD-3-Clause
*/
const xa=({ReactiveElement:a})=>{if(globalThis.ShadyCSS!==void 0&&(!globalThis.ShadyCSS.nativeShadow||globalThis.ShadyCSS.ApplyShim)){a=a.prototype;globalThis.ShadyDOM&&globalThis.ShadyDOM.inUse&&globalThis.ShadyDOM.noPatch===!0&&globalThis.ShadyDOM.patchElementProto(a);var b=a.aa;a.aa=function(){const e=this.localName;if(globalThis.ShadyCSS.nativeShadow)return b.call(this);if(!this.constructor.hasOwnProperty("__scoped")){this.constructor.__scoped=!0;const g=this.constructor.za.map(v=>v instanceof
CSSStyleSheet?Array.from(v.cssRules).reduce((x,n)=>x+n.cssText,""):v.cssText);let h,k;(h=globalThis.ShadyCSS)==null||(k=h.ScopingShim)==null||k.prepareAdoptedCssText(g,e);this.constructor.mb===void 0&&globalThis.ShadyCSS.prepareTemplateStyles(document.createElement("template"),e)}let f;return(f=this.shadowRoot)!=null?f:this.attachShadow(this.constructor.jb)};var c=a.connectedCallback;a.connectedCallback=function(){c.call(this);this.fa&&globalThis.ShadyCSS.styleElement(this)};var d=a.va;a.va=function(e){this.fa||
globalThis.ShadyCSS.styleElement(this);d.call(this,e)}}};let ya;(ya=globalThis).reactiveElementPolyfillSupport!=null||(ya.reactiveElementPolyfillSupport=xa);oa||qa||(qa=!0,q.HTMLElement=pa());const za=pa(),Aa=Object.is,Ba=Object.defineProperty,Ca=Object.getOwnPropertyDescriptor,Da=Object.getOwnPropertyNames,Ea=Object.getOwnPropertySymbols,Fa=Object.getPrototypeOf,Ga=q.trustedTypes,Ha=Ga?Ga.emptyScript:"",Ia=q.reactiveElementPolyfillSupport;
var z={kb(a,b){switch(b){case Boolean:a=a?Ha:null;break;case Object:case Array:a=a==null?a:JSON.stringify(a)}return a},cb(a,b){let c=a;switch(b){case Boolean:c=a!==null;break;case Number:c=a===null?null:Number(a);break;case Object:case Array:try{c=JSON.parse(a)}catch(d){c=null}}return c}},C=(a,b)=>!Aa(a,b);const Ja={ya:!0,type:String,ea:z,sa:!1,lb:!1,ib:C};var Ka;Symbol.metadata==null&&(Symbol.metadata=Symbol("metadata"));Ka=Symbol.metadata;var D=new WeakMap;
function La(a,b,c){var d=Symbol();let e;const {get:f,set:g}=(e=Ca(a.prototype,b))!=null?e:{get(){return this[d]},set(h){this[d]=h}};return{get:f,set(h){const k=f==null?void 0:f.call(this);g==null||g.call(this,h);E(this,b,k,c)},configurable:!0,enumerable:!0}}function Ma(a,b,c=Ja){c.state&&(c.ya=!1);a.g();a.prototype.hasOwnProperty(b)&&(c=Object.create(c),c.fb=!0);a.m.set(b,c);c.ec||(c=La(a,b,c),c!==void 0&&Ba(a.prototype,b,c))}
function E(a,b,c,d){if(b!==void 0){const e=a.constructor,f=a[b];d!=null||(d=Na(e,b));let g,h;if(((h=d.ib)!=null?h:C)(f,c)||d.lb&&d.sa&&f===((g=a.ba)==null?void 0:g.get(b))&&!a.hasAttribute(e.wa(b,d)))a.ja(b,c,d);else return}a.j===!1&&(a.qa=a.pb())}function Na(a,b){let c;return(c=a.m.get(b))!=null?c:Ja}
function Oa(a){if(a.j){if(!a.fa){a.ua!=null||(a.ua=a.aa());if(a.o){for(const [d,e]of a.o)a[d]=e;a.o=void 0}var b=a.constructor.m;if(b.size>0)for(const [d,e]of b){b=d;var c=e;const f=a[b];c.fb!==!0||a.i.has(b)||f===void 0||a.ja(b,void 0,c,f)}}b=!1;c=a.i;try{b=!0;let d;(d=a.ma)==null||d.forEach(e=>{let f;return(f=e.bc)==null?void 0:f.call(e)});a.update(c)}catch(d){throw b=!1,a.pa(),d;}b&&a.va(c)}}
var F=class extends za{static addInitializer(a){this.g();let b;((b=this.la)!=null?b:this.la=[]).push(a)}static get observedAttributes(){this.finalize();return this.oa&&[...this.oa.keys()]}static g(){if(!this.hasOwnProperty("m")){var a=Fa(this);a.finalize();a.la!==void 0&&(this.la=[...a.la]);this.m=new Map(a.m)}}static finalize(){Pa();if(!this.hasOwnProperty("bb")){this.bb=!0;this.g();if(this.hasOwnProperty("properties")){var a=this.properties,b=[...Da(a),...Ea(a)];for(const c of b)Ma(this,c,a[c])}a=
this[Ka];if(a!==null&&(a=D.get(a),a!==void 0))for(const [c,d]of a)this.m.set(c,d);this.oa=new Map;for(const [c,d]of this.m)a=c,b=this.wa(a,d),b!==void 0&&this.oa.set(b,a);b=this.styles;a=[];if(Array.isArray(b)){b=new Set(b.flat(Infinity).reverse());for(const c of b)a.unshift(wa(c))}else b!==void 0&&a.push(wa(b));this.za=a}}static wa(a,b){b=b.ya;return b===!1?void 0:typeof b==="string"?b:typeof a==="string"?a.toLowerCase():void 0}constructor(){super();this.o=void 0;this.fa=this.j=!1;this.g=null;this.rb()}rb(){this.qa=
new Promise(b=>this.ra=b);this.i=new Map;this.tb();E(this);let a;(a=this.constructor.la)==null||a.forEach(b=>b(this))}tb(){const a=new Map,b=this.constructor.m;for(const c of b.keys())this.hasOwnProperty(c)&&(a.set(c,this[c]),delete this[c]);a.size>0&&(this.o=a)}aa(){let a;const b=(a=this.shadowRoot)!=null?a:this.attachShadow(this.constructor.jb);va(b,this.constructor.za);return b}connectedCallback(){this.ua!=null||(this.ua=this.aa());this.ra(!0);let a;(a=this.ma)==null||a.forEach(b=>{let c;return(c=
b.zb)==null?void 0:c.call(b)})}ra(){}disconnectedCallback(){let a;(a=this.ma)==null||a.forEach(b=>{let c;return(c=b.ac)==null?void 0:c.call(b)})}attributeChangedCallback(a,b,c){this.ob(a,c)}sb(a,b){const c=this.constructor.m.get(a),d=this.constructor.wa(a,c);if(d!==void 0&&c.sa===!0){let e;const f=(((e=c.ea)==null?void 0:e.kb)!==void 0?c.ea:z).kb(b,c.type);this.g=a;f==null?this.removeAttribute(d):this.setAttribute(d,f);this.g=null}}ob(a,b){var c=this.constructor;a=c.oa.get(a);if(a!==void 0&&this.g!==
a){c=Na(c,a);let d;const e=typeof c.ea==="function"?{cb:c.ea}:((d=c.ea)==null?void 0:d.cb)!==void 0?c.ea:z;this.g=a;b=e.cb(b,c.type);let f,g;this[a]=(g=b!=null?b:(f=this.ba)==null?void 0:f.get(a))!=null?g:b;this.g=null}}ja(a,b,{lb:c,sa:d,fb:e},f){let g;if(c&&!((g=this.ba)!=null?g:this.ba=new Map).has(a)){let h;this.ba.set(a,(h=f!=null?f:b)!=null?h:this[a]);if(e!==!0||f!==void 0)return}this.i.has(a)||(this.fa||c||(b=void 0),this.i.set(a,b));if(d===!0&&this.g!==a){let h;((h=this.ca)!=null?h:this.ca=
new Set).add(a)}}async pb(){this.j=!0;try{await this.qa}catch(b){this.dc||Promise.reject(b)}const a=Oa(this);a!=null&&await a;return!this.j}va(a){let b;(b=this.ma)==null||b.forEach(c=>{let d;return(d=c.cc)==null?void 0:d.call(c)});this.fa||(this.fa=!0);this.updated(a)}pa(){this.i=new Map;this.j=!1}update(){this.ca&&(this.ca=this.ca.forEach(a=>this.sb(a,this[a])));this.pa()}updated(){}};F.za=[];F.jb={mode:"open"};F.m=new Map;F.bb=new Map;Ia==null||Ia({ReactiveElement:F});
let Pa=()=>{let a;((a=q.reactiveElementVersions)!=null?a:q.reactiveElementVersions=[]).push("2.0.4");Pa=()=>{}};const Qa={ya:!0,type:String,ea:z,sa:!1,ib:C};
var Ra=(a=Qa,b,c)=>{const d=c.kind,e=c.metadata;let f=D.get(e);f===void 0&&D.set(e,f=new Map);d==="setter"&&(a=Object.create(a),a.fb=!0);f.set(c.name,a);if(d==="accessor"){const g=c.name;return{set(h){const k=b.get.call(this);b.set.call(this,h);E(this,g,k,a)},init(h){h!==void 0&&this.ja(g,void 0,a,h);return h}}}if(d==="setter"){const g=c.name;return function(h){const k=this[g];b.call(this,h);E(this,g,k,a)}}throw Error(`Unsupported decorator location: ${d}`);};const Sa=new Set,Ta=new Map,Ua=(a,b)=>{if(globalThis.ShadyCSS!==void 0&&(!globalThis.ShadyCSS.nativeShadow||globalThis.ShadyCSS.ApplyShim)){var c,d,e=((c=globalThis.ShadyDOM)==null?0:c.inUse)&&((d=globalThis.ShadyDOM)==null?void 0:d.noPatch)===!0?globalThis.ShadyDOM.wrap:l=>l,f=l=>l!==void 0&&!Sa.has(l),g=l=>{let m=Ta.get(l);m===void 0&&Ta.set(l,m=[]);return m},h=(l,m)=>{const p=g(l),t=p.length!==0;if(t){const r=document.createElement("style");r.textContent=p.join("\n");m.content.appendChild(r)}Sa.add(l);
Ta.delete(l);globalThis.ShadyCSS.prepareTemplateStyles(m,l);t&&globalThis.ShadyCSS.nativeShadow&&(l=m.content.querySelector("style"),l!==null&&m.content.appendChild(l))},k=new Map,v=a.createElement;a.createElement=function(l,m){l=v.call(a,l,m);m=m==null?void 0:m.scope;if(m!==void 0&&(globalThis.ShadyCSS.nativeShadow||globalThis.ShadyCSS.prepareTemplateDom(l,m),f(m))){m=g(m);const p=l.content.querySelectorAll("style");m.push(...Array.from(p).map(t=>{let r;(r=t.parentNode)==null||r.removeChild(t);return t.textContent}))}return l};
var x=document.createDocumentFragment(),n=document.createComment("");b=b.prototype;var A=b.u;b.u=function(l,m=this){const p=e(this.v).parentNode;var t,r=(t=this.options)==null?void 0:t.scope,B;if((p instanceof ShadowRoot||p===((B=this.options)==null?void 0:B.fc))&&f(r)){t=this.v;B=this.ga;x.appendChild(n);this.v=n;this.ga=null;A.call(this,l,m);l=(l==null?0:l._$litType$)?this.h.na.ia:document.createElement("template");h(r,l);x.removeChild(n);let w;if((w=globalThis.ShadyCSS)==null?0:w.nativeShadow)r=
l.content.querySelector("style"),r!==null&&x.appendChild(r.cloneNode(!0));p.insertBefore(x,B);this.v=t;this.ga=B}else A.call(this,l,m)};b.gb=function(l){var m,p=(m=this.options)==null?void 0:m.scope;m=k.get(p);m===void 0&&k.set(p,m=new Map);p=m.get(l.l);p===void 0&&m.set(l.l,p=new a(l,this.options));return p}}};let Va;(Va=globalThis).litHtmlPolyfillSupport!=null||(Va.litHtmlPolyfillSupport=Ua);let Wa="";if(globalThis.Symbol){const a=Symbol();typeof a!=="symbol"&&(Wa=Object.keys(a)[0])}
const Xa=Wa!=="";var Za=Xa?a=>a!=null&&a[Wa]!==void 0:()=>!1;if(Xa&&!globalThis.Symbol.for){const a=new Map;globalThis.Symbol.for=b=>{a.has(b)||a.set(b,Symbol(b));return a.get(b)}};const $a=({LitElement:a})=>{if(globalThis.ShadyCSS!==void 0&&(!globalThis.ShadyCSS.nativeShadow||globalThis.ShadyCSS.ApplyShim)){a.mb=!0;a=a.prototype;var b=a.aa;a.aa=function(){this.ta.scope=this.localName;return b.call(this)}}};let ab;(ab=globalThis).litElementPolyfillSupport!=null||(ab.litElementPolyfillSupport=$a);/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
var bb=globalThis.trustedTypes;let cb=bb,db;function eb(){let a=null;if(!cb)return a;try{const b=c=>c;a=cb.createPolicy("goog#html",{createHTML:b,createScript:b,createScriptURL:b})}catch(b){}return a};var fb=class{constructor(){this.g=bb?bb.emptyHTML:""}toString(){return this.g+""}},gb;gb=new fb;function hb(a){if(a instanceof fb)return a.g;throw Error("");};var ib=class{constructor(a){this.g=a}toString(){return this.g+""}};function jb(a){var b;db===void 0&&(db=eb());a=(b=db)?b.createScriptURL(a):a;return new ib(a)}function kb(a){if(a instanceof ib)return a.g;throw Error("");};var G=lb;function lb(a,b,c){if(a.nodeType!==1)return mb;b=b.toLowerCase();if(b==="innerhtml"||b==="innertext"||b==="textcontent"||b==="outerhtml")return()=>hb(gb);const d=nb.get(`${a.tagName} ${b}`);return d!==void 0?d:/^on/.test(b)&&c==="attribute"&&(a=a.tagName.includes("-")?HTMLElement.prototype:a,b in a)?()=>{throw Error("invalid binding");}:mb}
const ob=/^(?!javascript:)(?:[a-z0-9+.-]+:|[^&:\/?#]*(?:[\/?#]|$))/i,pb=kb(function(a,...b){if(b.length===0)return jb(a[0]);let c=a[0];for(let d=0;d<b.length;d++)c+=encodeURIComponent(b[d])+a[d+1];return jb(c)}`about:invalid#zClosurez`),mb=a=>a,H=a=>ob.test(String(a))?a:pb,I=()=>pb,J=a=>a instanceof ib?kb(a):pb,nb=new Map([["A href",H],["AREA href",H],["BASE href",I],["BUTTON formaction",H],["EMBED src",I],["FORM action",H],["FRAME src",I],["IFRAME src",J],["IFRAME srcdoc",a=>a instanceof fb?hb(a):
hb(gb)],["INPUT formaction",H],["LINK href",J],["OBJECT codebase",I],["OBJECT data",I],["SCRIPT href",J],["SCRIPT src",J],["SCRIPT text",I],["USE href",J]]);let qb,rb,sb;
const K=((qb=q.ShadyDOM)==null?0:qb.inUse)&&(((rb=q.ShadyDOM)==null?void 0:rb.noPatch)===!0||((sb=q.ShadyDOM)==null?void 0:sb.noPatch)==="on-demand")?q.ShadyDOM.wrap:a=>a,L=q.trustedTypes,tb=L?L.createPolicy("lit-html",{createHTML:a=>a}):void 0,ub=a=>a,vb=()=>ub,M=`lit$${Math.random().toFixed(9).slice(2)}$`,wb="?"+M,xb=`<${wb}>`,N=document,O=a=>a===null||typeof a!="object"&&typeof a!="function"||Za(a),yb=Array.isArray,P=/<(?:(!--|\/[^a-zA-Z])|(\/?[a-zA-Z][^>\s]*)|(\/?$))/g,zb=/--\x3e/g,Ab=/>/g,Q=
RegExp(">|[ \t\n\f\r](?:([^\\s\"'>=/]+)([ \t\n\f\r]*=[ \t\n\f\r]*(?:[^ \t\n\f\r\"'`<>=]|(\"|')|))|$)","g"),Bb=/'/g,Cb=/"/g,Db=/^(?:script|style|textarea|title)$/i;var Eb=(a,...b)=>({_$litType$:1,l:a,values:b}),R=Symbol.for?Symbol.for("lit-noChange"):Symbol("lit-noChange"),S=Symbol.for?Symbol.for("lit-nothing"):Symbol("lit-nothing");const Fb=new WeakMap,T=N.createTreeWalker(N,129);
function Gb(a,b){if(!yb(a)||!a.hasOwnProperty("raw"))throw Error("invalid template strings array");return tb!==void 0?tb.createHTML(b):b}
var U=class{constructor({l:a,_$litType$:b},c){this.parts=[];let d=0,e=0;const f=a.length-1,g=this.parts;var h=a.length-1;const k=[];let v=b===2?"<svg>":b===3?"<math>":"",x,n=P;for(let p=0;p<h;p++){const t=a[p];let r=-1,B;var A=0;let w;for(;A<t.length;){n.lastIndex=A;w=n.exec(t);if(w===null)break;A=n.lastIndex;if(n===P)w[1]==="!--"?n=zb:w[1]!==void 0?n=Ab:w[2]!==void 0?(Db.test(w[2])&&(x=new RegExp(`</${w[2]}`,"g")),n=Q):w[3]!==void 0&&(n=Q);else if(n===Q)if(w[0]===">"){let Ya;n=(Ya=x)!=null?Ya:P;
r=-1}else w[1]===void 0?r=-2:(r=n.lastIndex-w[2].length,B=w[1],n=w[3]===void 0?Q:w[3]==='"'?Cb:Bb);else n===Cb||n===Bb?n=Q:n===zb||n===Ab?n=P:(n=Q,x=void 0)}A=n===Q&&a[p+1].startsWith("/>")?" ":"";v+=n===P?t+xb:r>=0?(k.push(B),t.slice(0,r)+"$lit$"+t.slice(r))+M+A:t+M+(r===-2?p:A)}a=[Gb(a,v+(a[h]||"<?>")+(b===2?"</svg>":b===3?"</math>":"")),k];const [l,m]=a;this.ia=U.createElement(l,c);T.currentNode=this.ia.content;if(b===2||b===3)b=this.ia.content.firstChild,b.replaceWith(...b.childNodes);for(;(b=
T.nextNode())!==null&&g.length<f;){if(b.nodeType===1){if(b.hasAttributes())for(const p of b.getAttributeNames())p.endsWith("$lit$")?(a=m[e++],c=b.getAttribute(p).split(M),a=/([.?@])?(.*)/.exec(a),g.push({type:1,index:d,name:a[2],l:c,nb:a[1]==="."?Hb:a[1]==="?"?Ib:a[1]==="@"?Jb:V}),b.removeAttribute(p)):p.startsWith(M)&&(g.push({type:6,index:d}),b.removeAttribute(p));if(Db.test(b.tagName)&&(c=b.textContent.split(M),a=c.length-1,a>0)){b.textContent=L?L.emptyScript:"";for(h=0;h<a;h++)b.append(c[h],N.createComment("")),
T.nextNode(),g.push({type:2,index:++d});b.append(c[a],N.createComment(""))}}else if(b.nodeType===8)if(b.data===wb)g.push({type:2,index:d});else for(c=-1;(c=b.data.indexOf(M,c+1))!==-1;)g.push({type:7,index:d}),c+=M.length-1;d++}}static createElement(a){const b=N.createElement("template");b.innerHTML=a;return b}};
function W(a,b,c=a,d){if(b===R)return b;var e;let f=d!==void 0?(e=c.i)==null?void 0:e[d]:c.pa;e=O(b)?void 0:b._$litDirective$;let g;if(((g=f)==null?void 0:g.constructor)!==e){let h,k;(h=f)==null||(k=h._$notifyDirectiveConnectionChanged)==null||k.call(h,!1);e===void 0?f=void 0:(f=new e(a),f.ub(a,c,d));if(d!==void 0){let v;((v=c.i)!=null?v:c.i=[])[d]=f}else c.pa=f}f!==void 0&&(b=W(a,f.wb(a,b.values),f,d));return b}
var Lb=class{constructor(a,b){this.i=[];this.ba=void 0;this.na=a;this.g=b}get parentNode(){return this.g.parentNode}get da(){return this.g.da}o(a){var b=this.na.ia.content;const c=this.na.parts;var d;const e=((d=a==null?void 0:a.xb)!=null?d:N).importNode(b,!0);T.currentNode=e;b=T.nextNode();let f=d=0,g=c[0];for(;g!==void 0;){if(d===g.index){let k;g.type===2?k=new X(b,b.nextSibling,this,a):g.type===1?k=new g.nb(b,g.name,g.l,this,a):g.type===6&&(k=new Kb(b,this,a));this.i.push(k);g=c[++f]}let h;d!==
((h=g)==null?void 0:h.index)&&(b=T.nextNode(),d++)}T.currentNode=N;return e}j(a){let b=0;for(const c of this.i)c!==void 0&&(c.l!==void 0?(c.u(a,c,b),b+=c.l.length-2):c.u(a[b])),b++}};function Mb(a,b){if(a.g===void 0){a.ja=b;let c;(c=a.ma)==null||c.call(a,b)}}
var X=class{get da(){let a,b;return(b=(a=this.g)==null?void 0:a.da)!=null?b:this.ja}constructor(a,b,c,d){this.type=2;this.h=S;this.ba=void 0;this.v=a;this.ga=b;this.g=c;this.options=d;let e;this.ja=(e=d==null?void 0:d.isConnected)!=null?e:!0;this.i=void 0}get parentNode(){let a=K(this.v).parentNode;const b=this.g;let c;b!==void 0&&((c=a)==null?void 0:c.nodeType)===11&&(a=b.parentNode);return a}u(a,b=this){a=W(this,a,b);O(a)?a===S||a==null||a===""?(this.h!==S&&this.j(),this.h=S):a!==this.h&&a!==R&&
this.ka(a):a._$litType$!==void 0?this.ra(a):a.nodeType!==void 0?this.o(a):yb(a)||typeof(a==null?void 0:a[Symbol.iterator])==="function"?this.qa(a):this.ka(a)}ca(a){return K(K(this.v).parentNode).insertBefore(a,this.ga)}o(a){if(this.h!==a){this.j();if(G!==vb){let b;const c=(b=this.v.parentNode)==null?void 0:b.nodeName;if(c==="STYLE"||c==="SCRIPT")throw Error("Forbidden");}this.h=this.ca(a)}}ka(a){if(this.h!==S&&O(this.h)){var b=K(this.v).nextSibling;this.i===void 0&&(this.i=G(b,"data","property"));
a=this.i(a);b.data=a}else b=N.createTextNode(""),this.o(b),this.i===void 0&&(this.i=G(b,"data","property")),a=this.i(a),b.data=a;this.h=a}ra(a){const {values:b,_$litType$:c}=a;a=typeof c==="number"?this.gb(a):(c.ia===void 0&&(c.ia=U.createElement(Gb(c.qb,c.qb[0]),this.options)),c);var d;((d=this.h)==null?void 0:d.na)===a?this.h.j(b):(d=new Lb(a,this),a=d.o(this.options),d.j(b),this.o(a),this.h=d)}gb(a){let b=Fb.get(a.l);b===void 0&&Fb.set(a.l,b=new U(a));return b}qa(a){yb(this.h)||(this.h=[],this.j());
const b=this.h;let c=0,d;for(const e of a)c===b.length?b.push(d=new X(this.ca(N.createComment("")),this.ca(N.createComment("")),this,this.options)):d=b[c],d.u(e),c++;c<b.length&&(this.j(d&&K(d.ga).nextSibling,c),b.length=c)}j(a=K(this.v).nextSibling,b){let c;for((c=this.ma)==null||c.call(this,!1,!0,b);a&&a!==this.ga;)b=K(a).nextSibling,K(a).remove(),a=b}},V=class{get tagName(){return this.element.tagName}get da(){return this.g.da}constructor(a,b,c,d,e){this.type=1;this.h=S;this.ba=void 0;this.element=
a;this.name=b;this.g=d;this.options=e;c.length>2||c[0]!==""||c[1]!==""?(this.h=Array(c.length-1).fill(new String),this.l=c):this.h=S;this.ha=void 0}u(a,b=this,c,d){const e=this.l;let f=!1;if(e===void 0){if(a=W(this,a,b,0),f=!O(a)||a!==this.h&&a!==R)this.h=a}else{const g=a;a=e[0];let h,k;for(h=0;h<e.length-1;h++){k=W(this,g[c+h],b,h);k===R&&(k=this.h[h]);f||(f=!O(k)||k!==this.h[h]);if(k===S)a=S;else if(a!==S){let v;a+=((v=k)!=null?v:"")+e[h+1]}this.h[h]=k}}f&&!d&&this.xa(a)}xa(a){if(a===S)K(this.element).removeAttribute(this.name);
else{this.ha===void 0&&(this.ha=G(this.element,this.name,"attribute"));let b;a=this.ha((b=a)!=null?b:"");let c;K(this.element).setAttribute(this.name,(c=a)!=null?c:"")}}},Hb=class extends V{constructor(){super(...arguments);this.type=3}xa(a){this.ha===void 0&&(this.ha=G(this.element,this.name,"property"));a=this.ha(a);this.element[this.name]=a===S?void 0:a}},Ib=class extends V{constructor(){super(...arguments);this.type=4}xa(a){K(this.element).toggleAttribute(this.name,!!a&&a!==S)}},Jb=class extends V{constructor(a,
b,c,d,e){super(a,b,c,d,e);this.type=5}u(a,b=this){var c;a=(c=W(this,a,b,0))!=null?c:S;if(a!==R){b=this.h;c=a===S&&b!==S||a.capture!==b.capture||a.once!==b.once||a.passive!==b.passive;var d=a!==S&&(b===S||c);c&&this.element.removeEventListener(this.name,this,b);d&&this.element.addEventListener(this.name,this,a);this.h=a}}handleEvent(a){if(typeof this.h==="function"){let b,c;this.h.call((c=(b=this.options)==null?void 0:b.host)!=null?c:this.element,a)}else this.h.handleEvent(a)}},Kb=class{constructor(a,
b,c){this.element=a;this.type=6;this.ba=void 0;this.g=b;this.options=c}get da(){return this.g.da}u(a){W(this,a)}};let Nb;(Nb=globalThis.litHtmlPolyfillSupport)==null||Nb(U,X);var Ob;let Pb;((Pb=q.litHtmlVersions)!=null?Pb:q.litHtmlVersions=[]).push("3.2.1");Ob=(a,b,c)=>{var d;const e=(d=c==null?void 0:c.eb)!=null?d:b;d=e._$litPart$;if(d===void 0){let f;d=(f=c==null?void 0:c.eb)!=null?f:null;e._$litPart$=d=new X(b.insertBefore(N.createComment(""),d),d,void 0,c!=null?c:{})}d.u(a);return d};var Y=class extends F{constructor(){super(...arguments);this.ta={host:this};this.ka=void 0}aa(){const a=super.aa();let b;(b=this.ta).eb!=null||(b.eb=a.firstChild);return a}update(a){const b=this.hb();this.fa||(this.ta.isConnected=this.isConnected);super.update(a);this.ka=Ob(b,this.ua,this.ta)}connectedCallback(){super.connectedCallback();let a;(a=this.ka)==null||Mb(a,!0)}disconnectedCallback(){super.disconnectedCallback();let a;(a=this.ka)==null||Mb(a,!1)}hb(){return R}static finalize(){Qb();return F.finalize.call(this)}};
Y._$litElement$=!0;Y.bb=!0;let Rb;(Rb=q.litElementPolyfillSupport)==null||Rb({LitElement:Y});let Qb=()=>{let a;((a=q.litElementVersions)!=null?a:q.litElementVersions=[]).push("4.1.1");Qb=()=>{}};var Sb=class extends Y{constructor(){super(...arguments);this.editing=!1}static get styles(){return[ua`
        /* div.rightActions is display:flex, so this must be display:block */
        :host {
          display: block;
        }
        /* display:inline is generally annoying, if we are not rendering text.
           display:block is easier to reason about when it comes to sizing and
           positioning. */
        gr-tooltip-content,
        a,
        svg {
          display: block;
        }
        gr-tooltip-content {
          margin-left: var(--spacing-l);
        }
        a {
          color: var(--deemphasized-text-color);
        }
      `]}hb(){if(this.editing)return Eb`
      <gr-tooltip-content has-tooltip title="About AI powered features">
        <a href="${"http://go/gob/users/ai-features"}" target="_blank"> ${Eb`
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="20"
        height="20"
        viewBox="-1 -1 20 20"
        fill="currentColor">
        <path
          fill="currentColor"
          fill-rule="evenodd"
          d="M8.963 13.5a.89.89 0 0 0 .656-.262.92.92 0 0 0 .281-.675.86.86 0 0 0-.281-.657.86.86 0 0 0-.656-.281.92.92 0 0 0-.675.281.89.89 0 0 0-.263.656c0 .263.088.488.262.676a.954.954 0 0 0 .675.262Zm-.675-2.887h1.387c0-.413.044-.738.131-.976.1-.237.369-.562.807-.975a5.86 5.86 0 0 0 .768-.918c.188-.3.281-.656.281-1.069 0-.7-.256-1.237-.768-1.612-.513-.375-1.119-.563-1.819-.563-.712 0-1.294.188-1.744.563a3.005 3.005 0 0 0-.919 1.35L7.65 6.9c.063-.225.2-.469.412-.731.226-.263.563-.394 1.013-.394.4 0 .7.112.9.337.2.213.3.45.3.713 0 .25-.075.487-.225.712a3.15 3.15 0 0 1-.563.6c-.55.488-.887.857-1.012 1.107s-.188.706-.188 1.369ZM9 16.5a7.405 7.405 0 0 1-2.925-.581 7.706 7.706 0 0 1-2.381-1.613 7.706 7.706 0 0 1-1.613-2.381A7.405 7.405 0 0 1 1.5 9c0-1.037.194-2.013.581-2.925.4-.913.938-1.706 1.613-2.381A7.445 7.445 0 0 1 6.075 2.1c.912-.4 1.888-.6 2.925-.6s2.012.2 2.925.6a7.444 7.444 0 0 1 2.381 1.594A7.445 7.445 0 0 1 15.9 6.075c.4.912.6 1.888.6 2.925 0 .539-.054 1.06-.162 1.566a4.109 4.109 0 0 0-1.396-.677C14.981 9.601 15 9.305 15 9c0-1.675-.581-3.094-1.744-4.256C12.094 3.58 10.675 3 9 3c-1.675 0-3.094.581-4.256 1.744C3.58 5.906 3 7.325 3 9c0 1.675.581 3.094 1.744 4.256C5.906 14.42 7.325 15 9 15c.305 0 .601-.02.89-.058.136.513.37.987.68 1.4A7.712 7.712 0 0 1 9 16.5Zm4.875 1.5c0-1.15-.4-2.125-1.2-2.925-.8-.8-1.775-1.2-2.925-1.2 1.15 0 2.125-.4 2.925-1.2.8-.8 1.2-1.775 1.2-2.925 0 1.15.4 2.125 1.2 2.925.8.8 1.775 1.2 2.925 1.2-1.15 0-2.125.4-2.925 1.2-.8.8-1.2 1.775-1.2 2.925Z"
          clip-rule="evenodd" />
      </svg>
    `} </a>
      </gr-tooltip-content>
    `}},Tb=function(a){return(b,c)=>{if(typeof c==="object")b=Ra(a,b,c);else{const d=b.hasOwnProperty(c);Ma(b.constructor,c,a);b=d?Object.getOwnPropertyDescriptor(b,c):void 0}return b}}({type:Boolean}),Ub;Ub=Reflect&&typeof Reflect==="object"&&typeof Reflect.metadata==="function"?Reflect.metadata("design:type",Object):void 0;ea([Tb,Ub],Sb.prototype,"editing",void 0);ea([(a=>(b,c)=>{c!==void 0?c.addInitializer(()=>{customElements.define(a,b)}):customElements.define(a,b)})("c2c-help-icon")],Sb);function Vb(a,b){if(!a.range)return!1;a=Wb(a.range);return a.start_line<=b.end_line+1&&a.start_line>=b.start_line&&a.end_line<=b.end_line}function Wb(a){return{start_line:a.start_line,start_character:a.start_char-1,end_line:a.end_line-1,end_character:a.end_char}}
function Xb(a,b,c){b=c!=null?c:Yb(b);var d=0;for(const f of a.replacements){var e=Wb(f.range);e=Z(f)-Math.max(0,e.end_line-e.start_line+1);e>0&&f.range.end_line<=b.start_line&&(d+=e);if(Vb(f,b))return e=0,f.range.end_line===b.start_line&&(e=Z(f)),d=b.start_line+d-e,a=a.new_content.split("\n").slice(d-1,d-1+(f.range.start_line===b.end_line+1||f.range.end_line===b.start_line?Z(f)+(b.end_line-b.start_line+1):Math.max(Z(f),b.end_line-b.start_line+1))).join("\n"),c?[{replacement:a,newRange:c}]:[{replacement:a}]}return[]}
function Zb(a){let b=void 0,c=0;for(const d of a.replacements)a=Z(d),c<a&&(c=a,b=Wb(d.range));return b}function Yb(a){let b;return(b=a.range)!=null?b:{start_line:a.lineNumber,end_line:a.lineNumber,start_character:0,end_character:0}}function Z(a){return a.new_content.split("\n").length-1};/*

 Copyright 2020 Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
const $b=["/COMMIT_MSG","/MERGE_LIST","/PATCHSET_LEVEL"];async function ac(a,b,c,d){return b===void 0||c===void 0||d===void 0?void 0:await a.restApi.post(`/changes/${b}/revisions/${c}/comment_autocompletion`,d,()=>{throw Error(`comment_autocompletion request for ${b} failed`);})}async function bc(a,b,c,d){if(b!==void 0&&c!==void 0&&d!==void 0)return await a.restApi.post(`/changes/${b}/revisions/${c}/prompt_to_edit`,d,()=>{throw Error(`request for ${b} failed`);})}
async function cc(a,b,c,d,e){if(d&&e)for(const f of b){if(!f.feedbackId){console.warn("Skipping Sending AI feedback, feedbackId is missing:",f);continue}b={feedback_id1:f.feedbackId.id1,feedback_id2:f.feedbackId.id2,yb:c,accepted:f.accepted};const g=`/changes/${d}/revisions/${e}/suggestion_feedback`;try{await a.restApi.post(g,b)}catch(h){console.error(`Failed to send suggestion feedback for change ${d}, revision ${e} with body ${JSON.stringify(b)}`,h)}}else console.warn("changeNum and revisionId are required for Send AI feedback.")}
function dc(a){let b;return(a==null?void 0:(b=a[0])==null?void 0:b.description)==="prompt_to_edit API"}
var ec=class{constructor(a){this.restApi=a.restApi()}async autocompleteComment(a){if(!a.commentText||a.changeInfo.is_private||$b.includes(a.filePath))return{completion:"",responseCode:"OK"};let b;try{b=await ac(this,a.changeInfo._number,a.patchsetNumber,{content:a.commentText,path:a.filePath,range:a.range,line:a.lineNumber,id:a.id,model:0})}catch(k){return console.error("Failed to request comment autocompletion",k),{responseCode:"ERROR"}}var c;a=(c=b)==null?void 0:c.model_name;var d;c=(d=b)==null?
void 0:d.comment_completion;let e;d=(e=b)==null?void 0:e.outcome;let f,g,h;((g=b)==null?void 0:g.feedback_id1)!==void 0&&((h=b)==null?void 0:h.feedback_id2)!==void 0&&(f={id1:b.feedback_id1,id2:b.feedback_id2});return{completion:c,modelVersion:a,outcome:d,feedback:f,responseCode:na(d)}}async suggestCode(a){if(!a.prompt)return{suggestions:[],responseCode:"ERROR"};if(a.changeInfo.is_private)return{suggestions:[],responseCode:"OK"};var b=a.prompt;const c=a.filePath,d=a.range,e=a.lineNumber;let f;try{f=
await bc(this,a.changeInfo._number,a.patchsetNumber,{prompt:b,filepath:c,range:d,line_nbr:e})}catch(h){return console.error("Failed to request suggested code",h),{suggestions:[],responseCode:"ERROR"}}var g;b=(g=f)==null?void 0:g[0];if(!b)return{suggestions:[],responseCode:"NO_SUGGESTION"};g=void 0;return b.replacements.some(h=>Vb(h,Yb(a)))||(g=Zb(b),g)?{suggestions:Xb(b,a,g),responseCode:"OK"}:{suggestions:[],responseCode:"OUT_OF_RANGE"}}async suggestFix(a){if(!a.prompt)return{fix_suggestions:[],
responseCode:"ERROR"};if(a.changeInfo.is_private)return{fix_suggestions:[],responseCode:"OK"};const b=a.prompt,c=a.filePath,d=a.range,e=a.lineNumber;let f;try{f=await bc(this,a.changeInfo._number,a.patchsetNumber,{prompt:b,filepath:c,range:d,line_nbr:e})}catch(h){return console.error("Failed to request suggested code",h),{fix_suggestions:[],responseCode:"ERROR"}}let g;return{fix_suggestions:((g=f)!=null?g:[]).map(h=>{let k;return{fix_id:`ml-${Math.random().toString(36).substring(2)}`,description:"prompt_to_edit API",
log_probability:h.log_probability,replacements:((k=h.replacements)!=null?k:[]).map(v=>{var x=v.range;return{path:c,range:{start_line:x.start_line,start_character:Math.max(x.start_char,0),end_line:x.end_line,end_character:Math.max(x.end_char,0)},replacement:v.new_content}})}}),responseCode:"OK"}}getFixSuggestionTitle(a){return!a||dc(a)?"AI-suggested fix":""}getDocumentationLink(a){return!a||dc(a)?"http://go/gob/users/ai-features#ai-suggested-fixes-v2":""}};window.Gerrit.install(async a=>{var b,c;if((b=await a.restApi().getAccount())==null?0:(c=b.tags)==null?0:c.includes("GOOGLER")){b=a.suggestions();const d=new ec(a);a.registerCustomComponent("comment","c2c-help-icon",{slot:"draft-actions-end"});a.registerCustomComponent("fix-suggestion-title-help","c2c-help-icon");c=new ma(a);a.aiCodeReview().register(c);b.register({autocompleteComment:e=>d.autocompleteComment(e),suggestCode:e=>d.suggestCode(e),suggestFix:e=>d.suggestFix(e),getFixSuggestionTitle:e=>
d.getFixSuggestionTitle(e),getDocumentationLink:e=>d.getDocumentationLink(e),sendAutocompleteFeedback:(e,f,g)=>{cc(d,e,"PREDICT_COMMENT",f,g)},sendSuggestFixFeedback:(e,f,g)=>{cc(d,e,"PREDICT_EDIT",f,g)},supportedFileExtensions:void 0})}});})();
//# sourceMappingURL=comments2code.js.sourcemap
