# Repository rules for in-tree or vendored sources.
#
# This module fragment is included from MODULE.bazel to keep repository
# declarations separate from the module dependency graph.

bazel_dep(name = "java-prettify")
git_override(
  module_name = "java-prettify",
  remote = "https://gerrit.googlesource.com/java-prettify",
  commit = "d50c5563fb7452966ee29ddeeec91fbc8a68d41f",
)
